import { NextResponse } from "next/server";
import dbConnect from "@/lib/db";
import Product from "@/models/Product";
import { getAuthUser, hasPermission } from "@/lib/auth";
import { syncGeneratedHardcopyForProductChange } from "@/lib/hardcopyAutoSync";
import { PHYSICAL_CATEGORY, normalizeProductCategory } from "@/lib/productCatalog";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import AdmZip from "adm-zip";

export const runtime = "nodejs";

const s3 = new S3Client({
  region: process.env.AWS_REGION!,
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
  },
});

const BUCKET = process.env.AWS_S3_BUCKET!;

const ALLOWED_EXT = ["jpg", "jpeg", "png", "webp"];
const MAX_IMAGES_PER_PRODUCT = 8;
const MAX_ZIP_SIZE = 100 * 1024 * 1024; // 100MB

function safeStr(x: any) {
  return String(x ?? "").trim();
}

function normalizeSku(input: string) {
  return safeStr(input).toUpperCase();
}

function uniqueStrings(arr: string[]) {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const v of arr) {
    const k = safeStr(v);
    if (!k || seen.has(k)) continue;
    seen.add(k);
    out.push(k);
  }
  return out;
}

function isValidImage(filename: string) {
  const ext = filename.split(".").pop()?.toLowerCase() || "";
  return ALLOWED_EXT.includes(ext);
}

function isLockedAutoGeneratedHardcopy(product: any) {
  return Boolean(product?.isAutoGenerated) && normalizeProductCategory(product?.category) === PHYSICAL_CATEGORY;
}

async function uploadToS3(buffer: Buffer, key: string, contentType: string) {
  await s3.send(
    new PutObjectCommand({
      Bucket: BUCKET,
      Key: key,
      Body: buffer,
      ContentType: contentType,
    })
  );

  return `https://${BUCKET}.s3.${process.env.AWS_REGION}.amazonaws.com/${key}`;
}

async function runHardcopySync(args: { before?: any; after?: any }) {
  try {
    return await syncGeneratedHardcopyForProductChange(args);
  } catch (syncErr: any) {
    return {
      ok: false,
      error: safeStr(syncErr?.message || "Hardcopy sync failed"),
    };
  }
}

export async function POST(req: Request) {
  const user = await getAuthUser();
  if (!user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });

  if (!hasPermission(user, "products:write")) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const formData = await req.formData();
  const file = formData.get("file") as File | null;

  if (!file) {
    return NextResponse.json({ error: "ZIP file required" }, { status: 400 });
  }

  if (!file.name.endsWith(".zip")) {
    return NextResponse.json({ error: "Only ZIP allowed" }, { status: 400 });
  }

  if (file.size > MAX_ZIP_SIZE) {
    return NextResponse.json({ error: "ZIP exceeds 100MB limit" }, { status: 400 });
  }

  const mode = safeStr(formData.get("mode")) || "append";
  // mode = "append" | "replace"

  const buffer = Buffer.from(await file.arrayBuffer());
  const zip = new AdmZip(buffer);
  const entries = zip.getEntries();

  await dbConnect();

  const folderMap = new Map<string, any[]>();

  for (const entry of entries) {
    if (entry.isDirectory) continue;

    const path = entry.entryName.replace(/\\/g, "/");

    if (path.startsWith("__MACOSX")) continue;

    const parts = path.split("/");
    if (parts.length < 2) continue;

    const folder = normalizeSku(parts[0]);
    const filename = parts[1];

    if (!isValidImage(filename)) continue;

    if (!folderMap.has(folder)) folderMap.set(folder, []);
    folderMap.get(folder)!.push(entry);
  }

  const items: any[] = [];
  let updated = 0;
  let notFound = 0;
  let failed = 0;
  let locked = 0;

  const hardcopySyncSummary = {
    attempted: 0,
    succeeded: 0,
    failed: 0,
    errors: [] as string[],
  };

  for (const [sku, imageEntries] of folderMap.entries()) {
    try {
      const product: any = await Product.findOne({ sku });
      if (!product) {
        items.push({ sku, status: "not_found" });
        notFound++;
        continue;
      }

      if (isLockedAutoGeneratedHardcopy(product)) {
        items.push({
          sku,
          status: "locked",
          reason:
            "Auto-generated Handwritten Hardcopy product par direct image upload blocked hai. Images source Solved Assignment product par upload karo.",
        });
        locked++;
        continue;
      }

      if (imageEntries.length === 0) {
        items.push({ sku, status: "no_images" });
        continue;
      }

      if (imageEntries.length > MAX_IMAGES_PER_PRODUCT) {
        items.push({
          sku,
          status: "failed",
          reason: `Max ${MAX_IMAGES_PER_PRODUCT} images allowed`,
        });
        failed++;
        continue;
      }

      const beforeProduct = product.toObject();

      const newImages: string[] = [];

      for (const entry of imageEntries) {
        const ext = entry.entryName.split(".").pop()!.toLowerCase();
        const contentType = `image/${ext === "jpg" ? "jpeg" : ext}`;

        const key = `products/${sku}/${Date.now()}-${Math.random()
          .toString(36)
          .substring(2)}.${ext}`;

        const imageBuffer = entry.getData();
        const url = await uploadToS3(imageBuffer, key, contentType);
        newImages.push(url);
      }

      if (mode === "replace") {
        product.images = newImages;
      } else {
        const combined = [...(Array.isArray(product.images) ? product.images : []), ...newImages];
        product.images = uniqueStrings(combined).slice(0, MAX_IMAGES_PER_PRODUCT);
      }

      const finalImages = Array.isArray(product.images) ? product.images : [];

      product.thumbnailUrl = finalImages[0] || "";
      product.quickUrl = finalImages[1] || finalImages[0] || "";
      product.lastModifiedAt = new Date();

      await product.save();

      const afterProduct = product.toObject();

      let hardcopySync: any = { ok: true, skipped: true };
      hardcopySyncSummary.attempted++;

      hardcopySync = await runHardcopySync({
        before: beforeProduct,
        after: afterProduct,
      });

      if (hardcopySync?.ok === false) {
        hardcopySyncSummary.failed++;
        if (safeStr(hardcopySync?.reason || hardcopySync?.error)) {
          hardcopySyncSummary.errors.push(safeStr(hardcopySync?.reason || hardcopySync?.error));
        }
      } else {
        hardcopySyncSummary.succeeded++;
      }

      items.push({
        sku,
        status: "updated",
        imageCount: newImages.length,
        totalImages: finalImages.length,
        hardcopySync: {
          ok: hardcopySync?.ok !== false,
          action: safeStr(hardcopySync?.action || ""),
          reason: safeStr(hardcopySync?.reason || hardcopySync?.error || ""),
        },
      });

      updated++;
    } catch (err: any) {
      items.push({
        sku,
        status: "failed",
        reason: err?.message || "Error",
      });
      failed++;
    }
  }

  hardcopySyncSummary.errors = uniqueStrings(hardcopySyncSummary.errors).slice(0, 10);

  return NextResponse.json({
    ok: true,
    summary: {
      totalFolders: folderMap.size,
      updated,
      skuNotFound: notFound,
      locked,
      failed,
    },
    hardcopySync: hardcopySyncSummary,
    items,
  });
}