import { NextResponse } from "next/server";
import dbConnect from "@/lib/db";
import Product from "@/models/Product";
import { getAuthUser, hasPermission } from "@/lib/auth";
import {
  syncGeneratedHardcopyForProductChange,
  SOLVED_ASSIGNMENTS_CATEGORY,
} from "@/lib/hardcopyAutoSync";
import { normalizeProductCategory } from "@/lib/productCatalog";

export const runtime = "nodejs";

function safeStr(x: any) {
  return String(x ?? "").trim();
}

function safeNum(x: any, def = 0) {
  const n = Number(x);
  return Number.isFinite(n) ? n : def;
}

export async function POST(req: Request) {
  try {
    const user = await getAuthUser();
    if (!user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });

    if (!hasPermission(user, "products:write")) {
      return NextResponse.json({ error: "Forbidden (products:write missing)" }, { status: 403 });
    }

    let body: any = {};
    try {
      body = await req.json();
    } catch {
      body = {};
    }

    const limit = Math.min(Math.max(Math.trunc(safeNum(body?.limit, 1000)), 1), 5000);
    const skuFilter = safeStr(body?.sku).toUpperCase();

    await dbConnect();

    const query: any = {
      deletedAt: null,
      isAutoGenerated: { $ne: true },
      category: SOLVED_ASSIGNMENTS_CATEGORY,
    };

    if (skuFilter) {
      query.sku = skuFilter;
    }

    const matchedCount = await Product.countDocuments(query);
    const sources: any[] = await Product.find(query)
      .sort({ updatedAt: -1, _id: -1 })
      .limit(limit);

    const items: any[] = [];

    let processed = 0;
    let created = 0;
    let updated = 0;
    let trashed = 0;
    let skipped = 0;
    let failed = 0;

    for (const source of sources) {
      processed++;

      try {
        const result: any = await syncGeneratedHardcopyForProductChange({
          after: source.toObject(),
        });

        const action = safeStr(result?.action || "unknown");
        const reason = safeStr(result?.reason || result?.error || "");
        const childSku = safeStr(result?.childSku || "");
        const childId = safeStr(result?.childId || "");

        if (result?.ok === false) {
          failed++;
        } else if (action === "created") {
          created++;
        } else if (action === "updated") {
          updated++;
        } else if (action === "trashed" || action === "already_trashed") {
          trashed++;
        } else {
          skipped++;
        }

        items.push({
          sourceSku: safeStr(source?.sku),
          sourceTitle: safeStr(source?.title),
          sourceAvailability: safeStr(source?.availability),
          sourceLanguage: safeStr(source?.language),
          childSku,
          childId,
          ok: result?.ok !== false,
          action,
          reason,
        });
      } catch (e: any) {
        failed++;
        items.push({
          sourceSku: safeStr(source?.sku),
          sourceTitle: safeStr(source?.title),
          sourceAvailability: safeStr(source?.availability),
          sourceLanguage: safeStr(source?.language),
          childSku: "",
          childId: "",
          ok: false,
          action: "exception",
          reason: safeStr(e?.message || "Unknown error"),
        });
      }
    }

    return NextResponse.json({
      ok: true,
      message: "Hardcopy backfill finished.",
      summary: {
        matchedCount,
        processed,
        created,
        updated,
        trashed,
        skipped,
        failed,
        hasMore: matchedCount > sources.length,
      },
      items,
    });
  } catch (error: any) {
    console.error("Hardcopy backfill error:", error);
    return NextResponse.json(
      {
        ok: false,
        error: error?.message || "Internal server error in hardcopy backfill",
      },
      { status: 500 }
    );
  }
}