import { NextRequest, NextResponse } from "next/server";

import dbConnect from "@/lib/db";
import Product from "@/models/Product";
import ProductImageVaultFile from "@/models/ProductImageVaultFile";
import { getAuthUser, hasPermission } from "@/lib/auth";
import { safeStr, normalizeSkuLike } from "@/lib/pdfVault";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type CsvMode = "missing-products" | "image-only-products";

const HARDCOPY_CATEGORY = "Handwritten Hardcopy (Delivery)";
const HARDCOPY_GENERATION_TYPE = "solved_assignment_hardcopy";

type CategoryStats = {
  category: string;
  totalProducts: number;
  totalProductsWithImages: number;
  totalProductsWithoutImages: number;
  totalImageOnlyWithoutProduct: number;
};

function csvEscape(value: any) {
  const text = String(value ?? "");
  if (/[",\n\r]/.test(text)) return `"${text.replace(/"/g, '""')}"`;
  return text;
}

function csvResponse(fileName: string, rows: string[][]) {
  const csv = rows.map((row) => row.map(csvEscape).join(",")).join("\n");

  return new NextResponse(csv, {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${fileName}"`,
      "Cache-Control": "no-store",
    },
  });
}

async function assertAdminWriteAccess() {
  const user = await getAuthUser();

  if (!user) {
    return {
      ok: false as const,
      res: NextResponse.json({ ok: false, error: "Not authenticated" }, { status: 401 }),
    };
  }

  if (!hasPermission(user, "products:write")) {
    return {
      ok: false as const,
      res: NextResponse.json({ ok: false, error: "Forbidden" }, { status: 403 }),
    };
  }

  return { ok: true as const, user };
}

function normalizeCategory(value: any) {
  return safeStr(value) || "Uncategorized";
}

function ensureCategoryStats(map: Map<string, CategoryStats>, category: string) {
  const key = normalizeCategory(category);

  if (!map.has(key)) {
    map.set(key, {
      category: key,
      totalProducts: 0,
      totalProductsWithImages: 0,
      totalProductsWithoutImages: 0,
      totalImageOnlyWithoutProduct: 0,
    });
  }

  return map.get(key)!;
}

function deriveSourceSkuForHardcopy(product: any) {
  const direct = normalizeSkuLike(product?.autoGeneratedFromSku);
  if (direct) return direct;

  const sku = normalizeSkuLike(product?.sku);
  if (sku.endsWith("D")) return `${sku.slice(0, -1)}A`;

  return "";
}

function isGeneratedHardcopy(product: any) {
  return (
    normalizeCategory(product?.category) === HARDCOPY_CATEGORY &&
    Boolean(product?.isAutoGenerated) &&
    safeStr(product?.autoGenerationType) === HARDCOPY_GENERATION_TYPE
  );
}

async function buildOverviewData() {
  await dbConnect();

  const products: any[] = await Product.find({ deletedAt: null })
    .select("sku title category isActive isAutoGenerated autoGenerationType autoGeneratedFromSku")
    .lean();

  const productMap = new Map<string, any>();
  const categoryMap = new Map<string, CategoryStats>();

  for (const product of products) {
    const sku = normalizeSkuLike(product.sku);
    if (!sku) continue;

    const category = normalizeCategory(product.category);

    productMap.set(sku, {
      ...product,
      sku,
      category,
      sourceSkuForImages: deriveSourceSkuForHardcopy(product),
    });

    ensureCategoryStats(categoryMap, category).totalProducts += 1;
  }

  const imageGroups: any[] = await ProductImageVaultFile.aggregate([
    { $match: { deletedAt: null } },
    {
      $group: {
        _id: "$skuNormalized",
        imageCount: { $sum: 1 },
        productSku: { $first: "$productSku" },
        latestUploadedAt: { $max: "$uploadedAt" },
      },
    },
  ]);

  const imageSkuSet = new Set<string>();
  const imageOnlyRows: any[] = [];

  for (const group of imageGroups) {
    const sku = normalizeSkuLike(group._id || group.productSku);
    if (!sku) continue;

    imageSkuSet.add(sku);

    if (!productMap.has(sku)) {
      imageOnlyRows.push({
        sku,
        category: "Product Not Found",
        imageCount: Number(group.imageCount || 0),
        latestUploadedAt: group.latestUploadedAt ? String(group.latestUploadedAt) : "",
      });

      ensureCategoryStats(categoryMap, "Product Not Found").totalImageOnlyWithoutProduct += 1;
    }
  }

  const productsWithImages: any[] = [];
  const productsWithoutImages: any[] = [];

  for (const [sku, product] of productMap.entries()) {
    const category = normalizeCategory(product.category);
    const stats = ensureCategoryStats(categoryMap, category);

    const sourceSku = safeStr(product.sourceSkuForImages);
    const hasOwnImages = imageSkuSet.has(sku);
    const hasSourceImages = isGeneratedHardcopy(product) && sourceSku && imageSkuSet.has(sourceSku);
    const hasImages = hasOwnImages || hasSourceImages;

    if (hasImages) {
      productsWithImages.push(product);
      stats.totalProductsWithImages += 1;
    } else {
      productsWithoutImages.push(product);
      stats.totalProductsWithoutImages += 1;
    }
  }

  productsWithImages.sort((a, b) => safeStr(a.sku).localeCompare(safeStr(b.sku)));
  productsWithoutImages.sort((a, b) => safeStr(a.sku).localeCompare(safeStr(b.sku)));
  imageOnlyRows.sort((a, b) => safeStr(a.sku).localeCompare(safeStr(b.sku)));

  const categories = Array.from(categoryMap.values()).sort((a, b) =>
    safeStr(a.category).localeCompare(safeStr(b.category))
  );

  return {
    totalProducts: productMap.size,
    totalProductsWithImages: productsWithImages.length,
    totalProductsWithoutImages: productsWithoutImages.length,
    totalImageOnlyWithoutProduct: imageOnlyRows.length,
    categories,
    productsWithoutImages,
    imageOnlyRows,
  };
}

export async function GET(req: NextRequest) {
  const guard = await assertAdminWriteAccess();
  if (!guard.ok) return guard.res;

  const { searchParams } = new URL(req.url);
  const download = safeStr(searchParams.get("download")) as CsvMode | "";
  const categoryFilter = safeStr(searchParams.get("category"));

  const data = await buildOverviewData();

  if (download === "missing-products") {
    const rows = data.productsWithoutImages.filter((product) => {
      if (!categoryFilter) return true;
      return normalizeCategory(product.category) === categoryFilter;
    });

    return csvResponse("products-without-images.csv", [
      ["SKU", "Title", "Category", "Status"],
      ...rows.map((product) => [
        safeStr(product.sku),
        safeStr(product.title),
        normalizeCategory(product.category),
        product.isActive ? "Active" : "Inactive",
      ]),
    ]);
  }

  if (download === "image-only-products") {
    const rows = data.imageOnlyRows.filter((row) => {
      if (!categoryFilter) return true;
      return normalizeCategory(row.category) === categoryFilter;
    });

    return csvResponse("image-folders-without-product.csv", [
      ["SKU", "Category", "Image Count", "Latest Uploaded At"],
      ...rows.map((row) => [
        safeStr(row.sku),
        normalizeCategory(row.category),
        String(row.imageCount || 0),
        safeStr(row.latestUploadedAt),
      ]),
    ]);
  }

  return NextResponse.json({
    ok: true,
    overview: {
      totalProducts: data.totalProducts,
      totalProductsWithImages: data.totalProductsWithImages,
      totalProductsWithoutImages: data.totalProductsWithoutImages,
      totalImageOnlyWithoutProduct: data.totalImageOnlyWithoutProduct,
      categories: data.categories,
    },
  });
}