import Combo from "@/models/Combo";
import { generatePyqCombosFromProducts } from "@/lib/comboPyq";
import { generateCombosFromRules } from "@/lib/comboEngine";

type ProductLike = {
  category?: string;
  subjectCode?: string;
  lang3?: string;
  language?: string;
  medium?: string;
  sku?: string;
};

type ComboScope = {
  categorySlug: string;
  subjectCode: string;
  lang3: string;
};

type SyncAllGeneratedCombosArgs = {
  includePyq?: boolean;
  includeGeneric?: boolean;
  genericCategorySlugs?: string[];
};

const GENERIC_CATEGORY_SLUGS = [
  "solved-assignments",
  "guess-papers",
  "ebooks-notes",
  "handwritten-pdfs",
  "handwritten-hardcopy",
  "projects-synopsis",
];

function safeStr(x: any) {
  return String(x ?? "").trim();
}

function normalizeSubjectCodeLoose(input: any) {
  return safeStr(input).toUpperCase().replace(/\s+/g, "").replace(/[^A-Z0-9]/g, "");
}

function normalizeLang3FromText(input: any) {
  const raw = safeStr(input).toUpperCase().replace(/[^A-Z]/g, "");
  if (!raw) return "";

  if (raw.startsWith("HIN") || raw === "HINDI") return "HIN";
  if (raw.startsWith("ENG") || raw === "ENGLISH") return "ENG";
  if (raw.startsWith("URD") || raw === "URDU") return "URD";

  return raw.slice(0, 3);
}

function parsePyqSku(skuInput: any) {
  const sku = safeStr(skuInput).toUpperCase().replace(/\s+/g, "");
  if (!sku) return null;

  const m = sku.match(/^([A-Z0-9]+?)([A-Z]{3})(JUN|DEC)(\d{2})Q$/i);
  if (!m) return null;

  return {
    sku,
    subjectCode: normalizeSubjectCodeLoose(m[1]),
    lang3: safeStr(m[2]).toUpperCase(),
    sessionToken: safeStr(m[3]).toUpperCase(),
    year2: safeStr(m[4]),
  };
}

function isPyqCategoryInput(category: any) {
  const c = safeStr(category).toLowerCase().replace(/\s+/g, " ").trim();
  return (
    c === "question papers (pyq)" ||
    c === "question papers" ||
    c === "question-papers" ||
    c === "pyq"
  );
}

function productCategoryToSlug(category: string) {
  const c = safeStr(category).toLowerCase().replace(/\s+/g, " ").trim();

  if (c === "solved assignments" || c === "solved-assignments") return "solved-assignments";
  if (c === "guess papers" || c === "guess-papers") return "guess-papers";
  if (c === "ebooks/notes" || c === "ebooks notes" || c === "ebooks-notes") return "ebooks-notes";
  if (c === "handwritten pdfs" || c === "handwritten-pdfs") return "handwritten-pdfs";
  if (
    c === "handwritten hardcopy (delivery)" ||
    c === "handwritten hardcopy" ||
    c === "handwritten-hardcopy"
  ) {
    return "handwritten-hardcopy";
  }
  if (c === "projects & synopsis" || c === "projects and synopsis" || c === "projects-synopsis") {
    return "projects-synopsis";
  }

  if (isPyqCategoryInput(category)) return "question-papers";

  return "";
}

function deriveSubjectCode(product?: ProductLike | null) {
  const direct = normalizeSubjectCodeLoose(product?.subjectCode);
  if (direct) return direct;

  const parsedSku = parsePyqSku(product?.sku);
  if (parsedSku?.subjectCode) return parsedSku.subjectCode;

  return "";
}

function deriveLang3(product?: ProductLike | null) {
  const direct = normalizeLang3FromText(product?.lang3);
  if (direct) return direct;

  const parsedSku = parsePyqSku(product?.sku);
  if (parsedSku?.lang3) return parsedSku.lang3;

  const fromLanguage = normalizeLang3FromText(product?.language || product?.medium);
  if (fromLanguage) return fromLanguage;

  return "";
}

function buildScopeFromProduct(product?: ProductLike | null): ComboScope | null {
  if (!product) return null;

  const categorySlug = productCategoryToSlug(safeStr(product.category));
  const subjectCode = deriveSubjectCode(product);
  const lang3 = deriveLang3(product);

  if (!categorySlug || !subjectCode || !lang3) return null;

  return {
    categorySlug,
    subjectCode,
    lang3,
  };
}

function dedupeScopes(scopes: Array<ComboScope | null | undefined>) {
  const map = new Map<string, ComboScope>();

  for (const scope of scopes) {
    if (!scope) continue;
    const key = `${scope.categorySlug}__${scope.subjectCode}__${scope.lang3}`;
    if (!map.has(key)) map.set(key, scope);
  }

  return Array.from(map.values());
}

function normalizeAutoComboPayload(input: any) {
  const comboKind = safeStr(input?.comboKind).toLowerCase();

  const sourceType =
    comboKind === "pyq_3y" || comboKind === "pyq_5y" ? "pyq_generated" : "generated";

  return {
    ...input,
    sourceType,
    status: "active",
    isActive: true,
    isAutoGenerated: true,
    deletedAt: null,
    deletedBy: "",
    lastGeneratedAt: new Date(),
    updatedBy: "system:auto-sync",
  };
}

async function upsertGeneratedCombo(rawCombo: any) {
  const combo = normalizeAutoComboPayload(rawCombo);
  const generationKey = safeStr(combo?.generationKey);

  if (!generationKey) {
    return {
      created: 0,
      updated: 0,
      skippedLocked: 0,
      skippedMissingKey: 1,
    };
  }

  const existing: any = await Combo.findOne({ generationKey })
    .select("_id isLockedByAdmin allowAutoRefresh")
    .lean();

  if (existing?.isLockedByAdmin || existing?.allowAutoRefresh === false) {
    return {
      created: 0,
      updated: 0,
      skippedLocked: 1,
      skippedMissingKey: 0,
    };
  }

  await Combo.updateOne(
    { generationKey },
    {
      $set: {
        ...combo,
        deletedAt: null,
        deletedBy: "",
        lastGeneratedAt: new Date(),
        updatedBy: "system:auto-sync",
      },
      $setOnInsert: {
        createdBy: "system:auto-sync",
      },
    },
    { upsert: true }
  );

  return {
    created: existing ? 0 : 1,
    updated: existing ? 1 : 0,
    skippedLocked: 0,
    skippedMissingKey: 0,
  };
}

async function syncAllPyqCombos() {
  const allPyqCombos = await generatePyqCombosFromProducts();

  const relevantGenerationKeys = allPyqCombos
    .map((c: any) => safeStr(c?.generationKey))
    .filter(Boolean);

  let created = 0;
  let updated = 0;
  let skippedLocked = 0;
  let skippedMissingKey = 0;
  let deletedStale = 0;

  for (const rawCombo of allPyqCombos) {
    const res = await upsertGeneratedCombo(rawCombo);
    created += Number(res.created || 0);
    updated += Number(res.updated || 0);
    skippedLocked += Number(res.skippedLocked || 0);
    skippedMissingKey += Number(res.skippedMissingKey || 0);
  }

  const staleFilter: any = {
    categorySlug: "question-papers",
    comboKind: { $in: ["pyq_3y", "pyq_5y"] },
    isAutoGenerated: true,
    sourceType: { $in: ["pyq_generated", "generated"] },
  };

  if (relevantGenerationKeys.length > 0) {
    staleFilter.generationKey = { $nin: relevantGenerationKeys };
  }

  const staleDocs: any[] = await Combo.find(staleFilter)
    .select("_id isLockedByAdmin allowAutoRefresh")
    .lean();

  const deletableIds = staleDocs
    .filter((doc) => !doc?.isLockedByAdmin && doc?.allowAutoRefresh !== false)
    .map((doc) => doc._id);

  if (deletableIds.length) {
    const res = await Combo.deleteMany({ _id: { $in: deletableIds } });
    deletedStale = Number(res?.deletedCount || 0);
  }

  return {
    kind: "pyq_full_resync",
    generatedCount: allPyqCombos.length,
    created,
    updated,
    skippedLocked,
    skippedMissingKey,
    deletedStale,
  };
}

async function syncGenericGeneratedByCategory(categorySlug: string) {
  const cleanCategorySlug = safeStr(categorySlug).toLowerCase();
  if (!cleanCategorySlug) {
    return {
      kind: "generic_category_resync",
      categorySlug: "",
      generatedCount: 0,
      created: 0,
      updated: 0,
      skippedLocked: 0,
      skippedMissingKey: 0,
      deletedStale: 0,
      matchedRuleCount: 0,
    };
  }

  const generatedResult = await generateCombosFromRules({ categorySlug: cleanCategorySlug });
  const generatedCombos = Array.isArray(generatedResult?.combos) ? generatedResult.combos : [];

  const relevantGenerationKeys = generatedCombos
    .map((c: any) => safeStr(c?.generationKey))
    .filter(Boolean);

  let created = 0;
  let updated = 0;
  let skippedLocked = 0;
  let skippedMissingKey = 0;
  let deletedStale = 0;

  for (const rawCombo of generatedCombos) {
    const res = await upsertGeneratedCombo(rawCombo);
    created += Number(res.created || 0);
    updated += Number(res.updated || 0);
    skippedLocked += Number(res.skippedLocked || 0);
    skippedMissingKey += Number(res.skippedMissingKey || 0);
  }

  const staleFilter: any = {
    categorySlug: cleanCategorySlug,
    comboKind: "auto",
    isAutoGenerated: true,
    sourceType: "generated",
  };

  if (relevantGenerationKeys.length > 0) {
    staleFilter.generationKey = { $nin: relevantGenerationKeys };
  }

  const staleDocs: any[] = await Combo.find(staleFilter)
    .select("_id isLockedByAdmin allowAutoRefresh")
    .lean();

  const deletableIds = staleDocs
    .filter((doc) => !doc?.isLockedByAdmin && doc?.allowAutoRefresh !== false)
    .map((doc) => doc._id);

  if (deletableIds.length) {
    const res = await Combo.deleteMany({ _id: { $in: deletableIds } });
    deletedStale = Number(res?.deletedCount || 0);
  }

  return {
    kind: "generic_category_resync",
    categorySlug: cleanCategorySlug,
    generatedCount: generatedCombos.length,
    created,
    updated,
    skippedLocked,
    skippedMissingKey,
    deletedStale,
    matchedRuleCount: Number(generatedResult?.matchedRuleCount || 0),
  };
}

export async function syncAllGeneratedCombos(args: SyncAllGeneratedCombosArgs = {}) {
  const includePyq = args.includePyq !== false;
  const includeGeneric = args.includeGeneric === true;

  const categories =
    Array.isArray(args.genericCategorySlugs) && args.genericCategorySlugs.length
      ? args.genericCategorySlugs.map((x) => safeStr(x).toLowerCase()).filter(Boolean)
      : GENERIC_CATEGORY_SLUGS;

  const results: any[] = [];

  if (includePyq) {
    results.push(await syncAllPyqCombos());
  }

  if (includeGeneric) {
    for (const categorySlug of categories) {
      results.push(await syncGenericGeneratedByCategory(categorySlug));
    }
  }

  return {
    ok: true,
    results,
  };
}

export async function syncGeneratedCombosForProductChange(args: {
  before?: ProductLike | null;
  after?: ProductLike | null;
}) {
  const scopes = dedupeScopes([
    buildScopeFromProduct(args.before || null),
    buildScopeFromProduct(args.after || null),
  ]);

  if (!scopes.length) {
    return {
      ok: true,
      syncedScopes: 0,
      results: [],
      reason: "No valid combo scope detected from changed product",
    };
  }

  const results: any[] = [];

  const hasPyqScope = scopes.some((scope) => scope.categorySlug === "question-papers");
  if (hasPyqScope) {
    results.push(await syncAllPyqCombos());
  }

  const genericCategorySet = Array.from(
    new Set(
      scopes
        .filter((scope) => scope.categorySlug !== "question-papers")
        .map((scope) => scope.categorySlug)
        .filter(Boolean)
    )
  );

  for (const categorySlug of genericCategorySet) {
    results.push(await syncGenericGeneratedByCategory(categorySlug));
  }

  return {
    ok: true,
    syncedScopes: scopes.length,
    results,
  };
}