import Product from "@/models/Product";
import ComboCategorySetting from "@/models/ComboCategorySetting";
import {
  calculateComboPricing,
  hasValidMasterDiscountPercent,
  normalizePercentDiscountValue,
} from "@/lib/comboPricing";
import { buildPyqComboThumbUrl } from "@/lib/thumbUrls";

export type PyqComboKind = "pyq_3y" | "pyq_5y";

export type PyqComboItem = {
  productId: string;
  title: string;
  slug: string;
  category: string;
  subjectCode: string;
  subjectTitleEn: string;
  subjectTitleHi: string;
  medium: string;
  lang3: string;
  session: string;
  session6: string;
  courseCodes: string[];
  courseTitles: string[];
  price: number;
  thumbUrl: string;
  sku?: string;
  updatedAt?: string;
};

export type GeneratedPyqCombo = {
  key: string;
  title: string;
  shortTitle: string;
  slug: string;
  categorySlug: "question-papers";
  categoryLabel: "Question Papers (PYQ)";
  comboKind: PyqComboKind;
  variant: "pyq";
  status: "active";
  isActive: true;
  isAutoGenerated: true;
  isMakeOwnComboAllowed: true;

  sourceType: "pyq_generated";
  sourceRuleId: null;
  sourceTemplateKey: string;
  generationKey: string;
  generationGroupKey: string;
  isLockedByAdmin: false;
  allowAutoRefresh: true;

  subjectCode: string;
  medium: string;
  lang3: string;
  sessionRangeLabel: string;
  courseCodes: string[];

  description: string;
  shortDescription: string;
  badge: string;
  itemsLabel: string;

  totalMrp: number;
  offerPrice: number;
  saveAmount: number;
  savePercent: number;
  priceLabel: string;
  saveLabel: string;
  mediumLabel: string;
  sessionLabel: string;

  pricingSnapshot: {
    discountType: "percent";
    discountValue: number;
  };

  thumbMode: "dynamic";
  thumbUrl: string;

  metaTitle: string;
  metaDescription: string;

  productIds: string[];
  itemsSnapshot: Array<{
    productId: string;
    title: string;
    slug: string;
    category: string;
    subjectCode: string;
    subjectTitleEn: string;
    subjectTitleHi: string;
    medium: string;
    lang3: string;
    session: string;
    session6: string;
    courseCodes: string[];
    courseTitles: string[];
    price: number;
    thumbUrl: string;
    sku?: string;
    updatedAt?: string;
  }>;

  rules: {
    minCoPurchaseUsers: 0;
    minProductsRequired: number;
    maxProductsAllowed: number;
    sameSubjectOnly: true;
    sameMediumOnly: true;
    sameCategoryOnly: true;
    useLatestSessionsOnly: true;
    latestProductCount: number;
    generatedFrom: string;
  };

  builderConfigSnapshot: {
    minProductsRequired: number;
    maxProductsAllowed: number;
    sameSubjectOnly: true;
    sameMediumOnly: true;
    sameCategoryOnly: true;
  };

  generatedFromRule: string;
};

function safeStr(x: any) {
  return String(x ?? "").trim();
}

function safeNum(x: any, def = 0) {
  const n = Number(x);
  return Number.isFinite(n) ? n : def;
}

function toSlug(input: any) {
  return safeStr(input)
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function buildThumbUrl(p: any) {
  return (
    safeStr(p?.thumbnailUrl) ||
    safeStr(p?.quickUrl) ||
    (Array.isArray(p?.images) && p.images[0] ? safeStr(p.images[0]) : "")
  );
}

function normalizeMedium(language: string, lang3: string) {
  const l = safeStr(language);
  if (l) return l;

  const x = safeStr(lang3).toUpperCase();
  if (x === "HIN") return "Hindi";
  if (x === "ENG") return "English";
  if (x === "URD") return "Urdu";
  return x || "";
}

function uniqueById<T extends { productId: string }>(arr: T[]) {
  const seen = new Set<string>();
  const out: T[] = [];

  for (const item of arr) {
    const id = safeStr(item.productId);
    if (!id || seen.has(id)) continue;
    seen.add(id);
    out.push(item);
  }

  return out;
}

function uniqueStrings(arr: any[], upper = false) {
  return Array.from(
    new Set(
      (Array.isArray(arr) ? arr : [])
        .map((x) => (upper ? safeStr(x).toUpperCase() : safeStr(x)))
        .filter(Boolean)
    )
  );
}

function normalizeCategory(x: any) {
  return safeStr(x).toLowerCase().replace(/\s+/g, " ").trim();
}

function isPyqCategory(x: any) {
  const v = normalizeCategory(x);
  return (
    v === "question papers (pyq)" ||
    v === "question-papers" ||
    v === "question papers" ||
    v === "pyq"
  );
}

function isAllowedPyqAvailability(x: any) {
  const v = safeStr(x).toLowerCase().trim();
  return v === "available" || v === "on_demand";
}

function monthOrderFromToken(token: string) {
  const v = safeStr(token).toUpperCase();

  if (v === "JAN" || v === "JANUARY") return 1;
  if (v === "FEB" || v === "FEBRUARY") return 2;
  if (v === "MAR" || v === "MARCH") return 3;
  if (v === "APR" || v === "APRIL") return 4;
  if (v === "MAY") return 5;
  if (v === "JUN" || v === "JUNE") return 6;
  if (v === "JUL" || v === "JULY") return 7;
  if (v === "AUG" || v === "AUGUST") return 8;
  if (v === "SEP" || v === "SEPT" || v === "SEPTEMBER") return 9;
  if (v === "OCT" || v === "OCTOBER") return 10;
  if (v === "NOV" || v === "NOVEMBER") return 11;
  if (v === "DEC" || v === "DECEMBER") return 12;

  return 0;
}

function normalizeMonthShort(token: string) {
  const month = monthOrderFromToken(token);
  if (month === 1) return "JAN";
  if (month === 2) return "FEB";
  if (month === 3) return "MAR";
  if (month === 4) return "APR";
  if (month === 5) return "MAY";
  if (month === 6) return "JUN";
  if (month === 7) return "JUL";
  if (month === 8) return "AUG";
  if (month === 9) return "SEP";
  if (month === 10) return "OCT";
  if (month === 11) return "NOV";
  if (month === 12) return "DEC";
  return "";
}

function normalizeYear2To4(yy: string) {
  const n = Number(safeStr(yy));
  if (!Number.isFinite(n)) return 0;
  return n < 100 ? 2000 + n : n;
}

function parsePyqSku(skuInput: any) {
  const sku = safeStr(skuInput).toUpperCase().replace(/\s+/g, "");
  if (!sku) return null;

  const m = sku.match(
    /^([A-Z0-9]+?)([A-Z]{3})(JAN|JANUARY|FEB|FEBRUARY|MAR|MARCH|APR|APRIL|MAY|JUN|JUNE|JUL|JULY|AUG|AUGUST|SEP|SEPT|SEPTEMBER|OCT|OCTOBER|NOV|NOVEMBER|DEC|DECEMBER)(\d{2})Q$/i
  );
  if (!m) return null;

  const subjectCode = safeStr(m[1]).toUpperCase();
  const lang3 = safeStr(m[2]).toUpperCase();
  const sessionTokenRaw = safeStr(m[3]).toUpperCase();
  const sessionToken = normalizeMonthShort(sessionTokenRaw);
  const year2 = safeStr(m[4]);
  const year4 = normalizeYear2To4(year2);
  const month = monthOrderFromToken(sessionTokenRaw);
  const rank = year4 * 100 + month;

  if (!subjectCode || !lang3 || !month || !year4 || !sessionToken) return null;

  return {
    sku,
    subjectCode,
    lang3,
    sessionToken,
    year2,
    year4,
    month,
    rank,
    derivedSession6: `${year4}${String(month).padStart(2, "0")}`,
    derivedSessionLabel: `${sessionToken}${year2}`,
  };
}

function sessionSortValue(session6: string, session: string) {
  const s6 = safeStr(session6);
  if (/^\d{6}$/.test(s6)) return Number(s6);

  const raw = safeStr(session).toUpperCase();
  const m1 = raw.match(
    /(JAN|JANUARY|FEB|FEBRUARY|MAR|MARCH|APR|APRIL|MAY|JUN|JUNE|JUL|JULY|AUG|AUGUST|SEP|SEPT|SEPTEMBER|OCT|OCTOBER|NOV|NOVEMBER|DEC|DECEMBER)[\s\-]*(\d{2,4})/i
  );

  if (m1) {
    const monRaw = m1[1].toUpperCase();
    const yyRaw = m1[2];
    const year = yyRaw.length === 2 ? Number(`20${yyRaw}`) : Number(yyRaw);
    const mm = monthOrderFromToken(monRaw);
    if (year && mm) return year * 100 + mm;
  }

  const nums = raw.replace(/\D/g, "");
  if (nums.length >= 6) return Number(nums.slice(0, 6));
  if (nums.length === 4) return Number(`${nums}00`);

  return 0;
}

function getPyqSortRank(item: Pick<PyqComboItem, "sku" | "session6" | "session">) {
  const parsed = parsePyqSku(item?.sku);
  if (parsed?.rank) return parsed.rank;
  return sessionSortValue(item?.session6 || "", item?.session || "");
}

function buildSessionRangeLabel(items: PyqComboItem[]) {
  if (!items.length) return "";

  const sorted = [...items].sort((a, b) => getPyqSortRank(b) - getPyqSortRank(a));
  const labels = sorted
    .map((x) => {
      const parsed = parsePyqSku(x?.sku);
      if (parsed?.derivedSessionLabel) return parsed.derivedSessionLabel;
      return safeStr(x.session);
    })
    .filter(Boolean);

  if (!labels.length) return "";

  const first = labels[0];
  const last = labels[labels.length - 1];

  if (first && last && first !== last) return `${first} to ${last}`;
  return first || "";
}

function buildComboTitle(subjectCode: string, medium: string, kind: PyqComboKind) {
  const yearsText = kind === "pyq_3y" ? "3 Year PYQ Combo" : "5 Year PYQ Combo";
  return `${subjectCode} ${medium} ${yearsText}`.replace(/\s+/g, " ").trim();
}

function buildShortTitle(subjectCode: string, medium: string, kind: PyqComboKind) {
  const label = kind === "pyq_3y" ? "3Y PYQ Combo" : "5Y PYQ Combo";
  return `${subjectCode} ${medium} ${label}`.replace(/\s+/g, " ").trim();
}

function buildDescription(args: {
  kind: PyqComboKind;
  subjectCode: string;
  medium: string;
  sessionRangeLabel: string;
}) {
  const yearsLabel = args.kind === "pyq_3y" ? "3 year" : "5 year";
  const countLabel = args.kind === "pyq_3y" ? "latest 6" : "latest 10";
  const range = safeStr(args.sessionRangeLabel);

  return `${args.subjectCode} ${args.medium} ${yearsLabel} PYQ combo with ${countLabel} previous year question paper products for the same subject and same medium${range ? ` covering ${range}` : ""}.`
    .replace(/\s+/g, " ")
    .trim();
}

function buildShortDescription(args: {
  kind: PyqComboKind;
  subjectCode: string;
  medium: string;
}) {
  const yearsLabel = args.kind === "pyq_3y" ? "3 year" : "5 year";
  return `${yearsLabel} PYQ combo for ${args.subjectCode} in ${args.medium}.`
    .replace(/\s+/g, " ")
    .trim();
}

function buildBadge(kind: PyqComboKind) {
  return kind === "pyq_3y" ? "Latest 6 Products" : "Latest 10 Products";
}

function buildItemsLabel(kind: PyqComboKind) {
  return kind === "pyq_3y" ? "3 Years Pattern" : "5 Years Pattern";
}

function pickItemsForKind(sorted: PyqComboItem[], kind: PyqComboKind) {
  return kind === "pyq_3y" ? sorted.slice(0, 6) : sorted.slice(0, 10);
}

function minRequiredForKind(kind: PyqComboKind) {
  return kind === "pyq_3y" ? 6 : 10;
}

function templateKeyForKind(kind: PyqComboKind) {
  return kind === "pyq_3y" ? "pyq_3y_default" : "pyq_5y_default";
}

function generationRuleForKind(kind: PyqComboKind) {
  return kind === "pyq_3y"
    ? "pyq-latest-6-by-sku-same-subject-same-medium"
    : "pyq-latest-10-by-sku-same-subject-same-medium";
}

function shouldTreatAsPyqProduct(p: any) {
  const parsed = parsePyqSku(p?.sku);
  return Boolean(parsed) || isPyqCategory(p?.category);
}

async function loadPyqDiscountPercent() {
  const setting: any = await ComboCategorySetting.findOne({
    categorySlug: "question-papers",
    isActive: true,
    comboEnabled: true,
  })
    .select({
      discountType: 1,
      discountValue: 1,
    })
    .lean();

  const discountType = safeStr(setting?.discountType).toLowerCase();
  const discountValue = normalizePercentDiscountValue(setting?.discountValue);

  if (discountType === "percent" && hasValidMasterDiscountPercent(discountValue)) {
    return discountValue;
  }

  return 20;
}

function createComboFromItems(args: {
  kind: PyqComboKind;
  subjectCode: string;
  medium: string;
  lang3: string;
  items: PyqComboItem[];
  groupCourseCodes: string[];
  groupKey: string;
  discountPercent: number;
}): GeneratedPyqCombo {
  const { kind, subjectCode, medium, lang3, items, groupCourseCodes, groupKey, discountPercent } =
    args;

  const latestProductCount = minRequiredForKind(kind);
  const pricing = calculateComboPricing(items, {
    discountType: "percent",
    discountValue: discountPercent,
    roundOfferPrice: true,
  });

  const title = buildComboTitle(subjectCode, medium, kind);
  const shortTitle = buildShortTitle(subjectCode, medium, kind);
  const sessionRangeLabel = buildSessionRangeLabel(items);
  const description = buildDescription({
    kind,
    subjectCode,
    medium,
    sessionRangeLabel,
  });
  const shortDescription = buildShortDescription({
    kind,
    subjectCode,
    medium,
  });

  const thumbUrl = buildPyqComboThumbUrl({
    years: kind === "pyq_5y" ? 5 : 3,
    code: subjectCode,
    medium: `${medium} Medium`,
    slug: toSlug(title),
    updatedAt: items.map((x) => safeStr(x.updatedAt)).filter(Boolean).join("|"),
    id: items.map((x) => safeStr(x.productId)).filter(Boolean).join("|"),
  });

  const generationKey = buildGenerationKey(subjectCode, lang3, kind);
  const generationGroupKey = buildGenerationGroupKey(subjectCode, lang3);
  const generatedFromRule = generationRuleForKind(kind);

  return {
    key: `${groupKey}__${kind}`,
    title,
    shortTitle,
    slug: toSlug(title),
    categorySlug: "question-papers",
    categoryLabel: "Question Papers (PYQ)",
    comboKind: kind,
    variant: "pyq",
    status: "active",
    isActive: true,
    isAutoGenerated: true,
    isMakeOwnComboAllowed: true,

    sourceType: "pyq_generated",
    sourceRuleId: null,
    sourceTemplateKey: templateKeyForKind(kind),
    generationKey,
    generationGroupKey,
    isLockedByAdmin: false,
    allowAutoRefresh: true,

    subjectCode,
    medium,
    lang3,
    sessionRangeLabel,
    courseCodes: groupCourseCodes,

    description,
    shortDescription,
    badge: buildBadge(kind),
    itemsLabel: buildItemsLabel(kind),

    totalMrp: pricing.totalMrp,
    offerPrice: pricing.offerPrice,
    saveAmount: pricing.saveAmount,
    savePercent: pricing.savePercent,
    priceLabel: pricing.priceLabel,
    saveLabel: pricing.saveLabel,
    mediumLabel: medium,
    sessionLabel: sessionRangeLabel,

    pricingSnapshot: {
      discountType: "percent",
      discountValue: discountPercent,
    },

    thumbMode: "dynamic",
    thumbUrl,

    metaTitle: title,
    metaDescription: description,

    productIds: items.map((x) => x.productId),
    itemsSnapshot: items.map((x) => ({ ...x })),

    rules: {
      minCoPurchaseUsers: 0,
      minProductsRequired: latestProductCount,
      maxProductsAllowed: latestProductCount,
      sameSubjectOnly: true,
      sameMediumOnly: true,
      sameCategoryOnly: true,
      useLatestSessionsOnly: true,
      latestProductCount,
      generatedFrom: generatedFromRule,
    },

    builderConfigSnapshot: {
      minProductsRequired: latestProductCount,
      maxProductsAllowed: latestProductCount,
      sameSubjectOnly: true,
      sameMediumOnly: true,
      sameCategoryOnly: true,
    },

    generatedFromRule,
  };
}

function buildGenerationKey(subjectCode: string, lang3: string, comboKind: PyqComboKind) {
  return `question-papers__${safeStr(subjectCode).toUpperCase()}__${safeStr(lang3).toUpperCase()}__${comboKind}`;
}

function buildGenerationGroupKey(subjectCode: string, lang3: string) {
  return `question-papers__${safeStr(subjectCode).toUpperCase()}__${safeStr(lang3).toUpperCase()}`;
}

export async function generatePyqCombosFromProducts() {
  const discountPercent = await loadPyqDiscountPercent();

  const rawProducts: any[] = await Product.find({
    isActive: true,
    availability: { $in: ["available", "on_demand"] },
    $or: [{ deletedAt: null }, { deletedAt: { $exists: false } }],
  })
    .select({
      _id: 1,
      sku: 1,
      title: 1,
      slug: 1,
      category: 1,
      subjectCode: 1,
      subjectTitleEn: 1,
      subjectTitleHi: 1,
      courseCodes: 1,
      courseTitles: 1,
      language: 1,
      lang3: 1,
      session: 1,
      session6: 1,
      price: 1,
      thumbnailUrl: 1,
      quickUrl: 1,
      images: 1,
      availability: 1,
      updatedAt: 1,
    })
    .lean();

  const grouped = new Map<string, PyqComboItem[]>();

  for (const p of rawProducts || []) {
    if (!isAllowedPyqAvailability(p?.availability)) continue;
    if (!shouldTreatAsPyqProduct(p)) continue;

    const parsedSku = parsePyqSku(p?.sku);

    const subjectCode = safeStr(parsedSku?.subjectCode || p?.subjectCode).toUpperCase();
    const lang3 = safeStr(parsedSku?.lang3 || p?.lang3).toUpperCase();
    const medium = normalizeMedium(safeStr(p?.language || p?.medium), lang3);

    if (!subjectCode || !lang3) continue;

    const key = `${subjectCode}__${lang3}`;

    const item: PyqComboItem = {
      productId: String(p?._id || ""),
      sku: safeStr(p?.sku).toUpperCase(),
      title: safeStr(p?.title),
      slug: safeStr(p?.slug),
      category: safeStr(p?.category),
      subjectCode,
      subjectTitleEn: safeStr(p?.subjectTitleEn),
      subjectTitleHi: safeStr(p?.subjectTitleHi),
      medium,
      lang3,
      session: safeStr(p?.session || parsedSku?.derivedSessionLabel),
      session6: safeStr(p?.session6 || parsedSku?.derivedSession6),
      courseCodes: uniqueStrings(p?.courseCodes || [], true),
      courseTitles: uniqueStrings(p?.courseTitles || [], false),
      price: Math.max(0, safeNum(p?.price, 0)),
      thumbUrl: buildThumbUrl(p),
      updatedAt: safeStr(p?.updatedAt),
    };

    const existing = grouped.get(key) || [];
    existing.push(item);
    grouped.set(key, existing);
  }

  const combos: GeneratedPyqCombo[] = [];

  for (const [groupKey, items] of grouped.entries()) {
    const sorted = uniqueById(items).sort((a, b) => getPyqSortRank(b) - getPyqSortRank(a));

    if (!sorted.length) continue;

    const subjectCode = safeStr(sorted[0]?.subjectCode).toUpperCase();
    const medium = safeStr(sorted[0]?.medium);
    const lang3 = safeStr(sorted[0]?.lang3).toUpperCase();

    const groupCourseCodes = uniqueStrings(
      sorted.flatMap((x) => (Array.isArray(x.courseCodes) ? x.courseCodes : [])),
      true
    );

    const comboKinds: PyqComboKind[] = ["pyq_3y", "pyq_5y"];

    for (const kind of comboKinds) {
      const required = minRequiredForKind(kind);
      const selectedItems = pickItemsForKind(sorted, kind);

      if (selectedItems.length < required) continue;

      combos.push(
        createComboFromItems({
          kind,
          subjectCode,
          medium,
          lang3,
          items: selectedItems,
          groupCourseCodes,
          groupKey,
          discountPercent,
        })
      );
    }
  }

  return combos.sort((a, b) => {
    if (a.subjectCode !== b.subjectCode) return a.subjectCode.localeCompare(b.subjectCode);
    if (a.lang3 !== b.lang3) return a.lang3.localeCompare(b.lang3);
    return a.comboKind.localeCompare(b.comboKind);
  });
}