import { NextResponse } from "next/server";

import dbConnect from "@/lib/db";
import Product from "@/models/Product";
import { getAuthUser, hasPermission } from "@/lib/auth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 300;

const SOURCE_CATEGORY = "Solved Assignments";
const HARDCOPY_CATEGORY = "Handwritten Hardcopy (Delivery)";
const HARDCOPY_TYPE = "solved_assignment_hardcopy";

function safeStr(x: any) {
  return String(x ?? "").trim();
}

function safeArr(x: any) {
  if (Array.isArray(x)) return x.map((v) => safeStr(v)).filter(Boolean);
  return [];
}

function normalizeSkuLike(input: any) {
  return safeStr(input).toUpperCase().replace(/[^A-Z0-9]/g, "");
}

function buildHardcopySku(sourceSku: any) {
  const sku = normalizeSkuLike(sourceSku);
  if (!sku) return "";
  if (sku.endsWith("A")) return `${sku.slice(0, -1)}D`;
  return `${sku}D`;
}

export async function POST(req: Request) {
  try {
    const user = await getAuthUser();
    if (!user) {
      return NextResponse.json({ ok: false, error: "Not authenticated" }, { status: 401 });
    }

    if (!hasPermission(user, "products:write")) {
      return NextResponse.json({ ok: false, error: "Forbidden" }, { status: 403 });
    }

    let body: any = {};
    try {
      body = await req.json();
    } catch {
      body = {};
    }

    const dryRun = body?.dryRun !== false;

    await dbConnect();

    const sources: any[] = await Product.find({
      deletedAt: null,
      isAutoGenerated: { $ne: true },
      category: SOURCE_CATEGORY,
      images: { $exists: true, $ne: [] },
    })
      .select("_id sku title images thumbnailUrl quickUrl")
      .sort({ updatedAt: -1, _id: -1 });

    let processed = 0;
    let updated = 0;
    let skippedNoChild = 0;
    let skippedNoImages = 0;
    let skippedAlreadySame = 0;
    let failed = 0;

    const items: any[] = [];

    for (const source of sources) {
      processed += 1;

      try {
        const sourceImages = safeArr(source.images);
        const sourceThumbnail = safeStr(source.thumbnailUrl) || sourceImages[0] || "";
        const sourceQuick = safeStr(source.quickUrl) || sourceImages[1] || sourceImages[0] || "";

        if (!sourceImages.length) {
          skippedNoImages += 1;
          continue;
        }

        const sourceSku = normalizeSkuLike(source.sku);
        const childSku = buildHardcopySku(sourceSku);

        const child: any = await Product.findOne({
          deletedAt: null,
          category: HARDCOPY_CATEGORY,
          $or: [
            { sku: childSku },
            {
              isAutoGenerated: true,
              autoGenerationType: HARDCOPY_TYPE,
              autoGeneratedFromProductId: source._id,
            },
            {
              isAutoGenerated: true,
              autoGenerationType: HARDCOPY_TYPE,
              autoGeneratedFromSku: sourceSku,
            },
          ],
        });

        if (!child) {
          skippedNoChild += 1;
          items.push({
            sourceSku,
            childSku,
            action: "skipped_no_child",
            reason: "Generated hardcopy product not found.",
          });
          continue;
        }

        const childImages = safeArr(child.images);
        const sameImages = JSON.stringify(childImages) === JSON.stringify(sourceImages);
        const sameThumbnail = safeStr(child.thumbnailUrl) === sourceThumbnail;
        const sameQuick = safeStr(child.quickUrl) === sourceQuick;

        if (sameImages && sameThumbnail && sameQuick) {
          skippedAlreadySame += 1;
          items.push({
            sourceSku,
            childSku: safeStr(child.sku),
            action: "already_same",
          });
          continue;
        }

        if (!dryRun) {
          child.images = sourceImages;
          child.thumbnailUrl = sourceThumbnail;
          child.quickUrl = sourceQuick;
          child.lastModifiedAt = new Date();
          await child.save();
        }

        updated += 1;

        items.push({
          sourceSku,
          childSku: safeStr(child.sku),
          action: dryRun ? "would_update" : "updated",
          imageCount: sourceImages.length,
        });
      } catch (e: any) {
        failed += 1;
        items.push({
          sourceSku: safeStr(source?.sku),
          action: "failed",
          reason: safeStr(e?.message || "Unknown error"),
        });
      }
    }

    return NextResponse.json({
      ok: true,
      dryRun,
      message: dryRun
        ? "Preview complete. Run again with dryRun:false to apply."
        : "Hardcopy images backfill complete.",
      summary: {
        sourceProductsWithImages: sources.length,
        processed,
        updated,
        skippedNoChild,
        skippedNoImages,
        skippedAlreadySame,
        failed,
      },
      items: items.slice(0, 500),
    });
  } catch (e: any) {
    return NextResponse.json(
      {
        ok: false,
        error: safeStr(e?.message || "Hardcopy image backfill failed"),
      },
      { status: 500 }
    );
  }
}