"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  Boxes,
  ArrowRight,
  ShieldCheck,
  Search,
  RefreshCcw,
  Plus,
  X,
  CheckCircle2,
  AlertCircle,
  Pencil,
  Trash2,
  Loader2,
  SlidersHorizontal,
  Lock,
  Unlock,
  RotateCcw,
  Archive,
  PackageCheck,
} from "lucide-react";
import Image from "next/image";

type ComboRecord = {
  _id?: string;
  title?: string;
  slug?: string;
  shortTitle?: string;
  description?: string;
  shortDescription?: string;
  categorySlug?: string;
  categoryLabel?: string;
  comboKind?: string;
  variant?: string;
  status?: string;
  isActive?: boolean;
  isAutoGenerated?: boolean;
  isMakeOwnComboAllowed?: boolean;
  isLockedByAdmin?: boolean;
  allowAutoRefresh?: boolean;
  sourceType?: string;
  generationKey?: string;
  subjectCode?: string;
  medium?: string;
  lang3?: string;
  sessionRangeLabel?: string;
  badge?: string;
  itemsLabel?: string;
  totalMrp?: number;
  offerPrice?: number;
  saveAmount?: number;
  savePercent?: number;
  metaTitle?: string;
  metaDescription?: string;
  sortOrder?: number;
  productIds?: string[];
  itemsSnapshot?: Array<{
    productId?: string;
    title?: string;
    medium?: string;
    session?: string;
    subjectCode?: string;
    courseCodes?: string[];
    thumbUrl?: string;
  }>;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string | null;
};

type CombosResponse = {
  ok?: boolean;
  count?: number;
  combos?: ComboRecord[];
  error?: string;
};

type AdminProduct = {
  _id?: string;
  title?: string;
  slug?: string;
  category?: string;
  subjectCode?: string;
  subjectTitleEn?: string;
  subjectTitleHi?: string;
  courseCodes?: string[];
  courseTitles?: string[];
  session?: string;
  session6?: string;
  language?: string;
  lang3?: string;
  price?: number;
  thumbnailUrl?: string;
  quickUrl?: string;
  images?: string[];
  isActive?: boolean;
  deletedAt?: string | null;
};

type AdminProductsResponse = {
  ok?: boolean;
  count?: number;
  products?: AdminProduct[];
  error?: string;
};

type ComboCategorySettingRecord = {
  id?: string;
  categorySlug?: string;
  categoryLabel?: string;
  isActive?: boolean;
  comboEnabled?: boolean;
  manualCombosEnabled?: boolean;
  makeOwnComboEnabled?: boolean;
  discountType?: string;
  discountValue?: number;
  builderRules?: {
    minProductsRequired?: number;
    maxProductsAllowed?: number;
    sameCategoryOnly?: boolean;
    sameSubjectOnly?: boolean;
    sameMediumOnly?: boolean;
  };
  ui?: {
    makeOwnComboText?: string;
  };
};

type ComboCategorySettingsResponse = {
  ok?: boolean;
  count?: number;
  settings?: ComboCategorySettingRecord[];
  error?: string;
};

const CATEGORY_OPTIONS = [
  { value: "solved-assignments", label: "Solved Assignments", productCategory: "Solved Assignments" },
  { value: "question-papers", label: "Question Papers (PYQ)", productCategory: "Question Papers (PYQ)" },
  { value: "guess-papers", label: "Guess Papers", productCategory: "Guess Papers" },
  { value: "ebooks-notes", label: "eBooks/Notes", productCategory: "eBooks/Notes" },
  { value: "handwritten-pdfs", label: "Handwritten PDFs", productCategory: "Handwritten PDFs" },
  { value: "handwritten-hardcopy", label: "Handwritten Hardcopy (Delivery)", productCategory: "Handwritten Hardcopy (Delivery)" },
  { value: "projects-synopsis", label: "Projects & Synopsis", productCategory: "Projects & Synopsis" },
];

const COMBO_KIND_OPTIONS = [
  { value: "admin", label: "Admin Combo" },
  { value: "custom", label: "Custom Combo" },
  { value: "pyq_3y", label: "PYQ 3 Years" },
  { value: "pyq_5y", label: "PYQ 5 Years" },
];

const STATUS_OPTIONS = [
  { value: "draft", label: "Draft" },
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
];

function safeStr(x: any) {
  return String(x ?? "").trim();
}

function safeNum(x: any, def = 0) {
  const n = Number(x);
  return Number.isFinite(n) ? n : def;
}

function money(n: number) {
  try {
    return new Intl.NumberFormat("en-IN").format(Number(n || 0));
  } catch {
    return String(n || 0);
  }
}

function labelFromCategorySlug(slug: string) {
  const found = CATEGORY_OPTIONS.find((x) => x.value === slug);
  return found?.label || slug;
}

function productCategoryFromCategorySlug(slug: string) {
  const found = CATEGORY_OPTIONS.find((x) => x.value === slug);
  return found?.productCategory || "";
}

function inferVariant(categorySlug: string, comboKind: string) {
  if (comboKind === "pyq_3y" || comboKind === "pyq_5y" || categorySlug === "question-papers") {
    return "pyq";
  }
  if (categorySlug === "handwritten-hardcopy") return "hardcopy";
  return "default";
}

function buildThumbUrl(p: AdminProduct) {
  return (
    safeStr(p?.thumbnailUrl) ||
    safeStr(p?.quickUrl) ||
    (Array.isArray(p?.images) && p.images[0] ? safeStr(p.images[0]) : "")
  );
}

function sessionSortValue(session6: string, session: string) {
  const s6 = safeStr(session6);
  if (/^\d{6}$/.test(s6)) return Number(s6);

  const raw = safeStr(session).toUpperCase();
  const m = raw.match(/(JUN|JUNE|DEC|DECEMBER)[\s\-]*(\d{2,4})/i);
  if (m) {
    const monRaw = m[1].toUpperCase();
    const yyRaw = m[2];
    const year = yyRaw.length === 2 ? Number(`20${yyRaw}`) : Number(yyRaw);
    const mm = monRaw.startsWith("JUN") ? 6 : 12;
    return year * 100 + mm;
  }

  const nums = raw.replace(/\D/g, "");
  if (nums.length >= 6) return Number(nums.slice(0, 6));
  if (nums.length === 4) return Number(`${nums}00`);
  return 0;
}

function isValidMasterDiscount(setting?: ComboCategorySettingRecord | null) {
  if (!setting) return false;
  const discountType = safeStr(setting.discountType).toLowerCase();
  const discountValue = Math.max(0, Math.min(100, Number(setting.discountValue || 0)));
  return !!setting.isActive && !!setting.comboEnabled && discountType === "percent" && discountValue > 0;
}

function calculatePricingPreview(totalMrp: number, discountPercent: number) {
  const cleanMrp = Math.max(0, Number(totalMrp || 0));
  const cleanDiscount = Math.max(0, Math.min(100, Number(discountPercent || 0)));
  const rawOffer = cleanMrp * (1 - cleanDiscount / 100);
  const offerPrice = Math.max(0, Math.round(rawOffer));
  const saveAmount = Math.max(0, cleanMrp - offerPrice);
  const savePercent =
    cleanMrp > 0 ? Math.max(0, Math.min(100, Math.round((saveAmount / cleanMrp) * 100))) : 0;

  return {
    totalMrp: cleanMrp,
    offerPrice,
    saveAmount,
    savePercent,
  };
}

function defaultForm() {
  return {
    title: "",
    shortTitle: "",
    categorySlug: "solved-assignments",
    comboKind: "admin",
    status: "draft",
    subjectCode: "",
    medium: "",
    lang3: "",
    sessionRangeLabel: "",
    description: "",
    shortDescription: "",
    badge: "",
    itemsLabel: "Included Bundle Items",
    sortOrder: "0",
    metaTitle: "",
    metaDescription: "",
    isActive: false,
    isMakeOwnComboAllowed: true,
  };
}

function SectionCard({
  title,
  subtitle,
  icon,
  actions,
  children,
}: {
  title: string;
  subtitle?: string;
  icon: React.ReactNode;
  actions?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-3xl border border-gray-200 bg-white shadow-sm overflow-hidden">
      <div className="p-5 border-b border-gray-100 flex items-start justify-between gap-4 flex-wrap">
        <div className="flex items-start gap-3">
          <div className="h-11 w-11 rounded-2xl bg-gray-100 flex items-center justify-center shrink-0">
            {icon}
          </div>
          <div>
            <div className="text-lg font-extrabold text-slate-900">{title}</div>
            {subtitle ? <div className="text-sm text-slate-600 mt-1">{subtitle}</div> : null}
          </div>
        </div>
        {actions ? <div className="flex items-center gap-2 flex-wrap">{actions}</div> : null}
      </div>
      <div className="p-5">{children}</div>
    </div>
  );
}

export default function AdminCombosPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [deletingId, setDeletingId] = useState("");
  const [editingId, setEditingId] = useState("");
  const [message, setMessage] = useState<{ type: "success" | "error" | ""; text: string }>({
    type: "",
    text: "",
  });

  const [search, setSearch] = useState("");
  const [filterCategory, setFilterCategory] = useState("");
  const [filterStatus, setFilterStatus] = useState("");
  const [trashMode, setTrashMode] = useState(false);

  const [combos, setCombos] = useState<ComboRecord[]>([]);
  const [categorySettingsMap, setCategorySettingsMap] = useState<
    Record<string, ComboCategorySettingRecord>
  >({});

  const [availableProducts, setAvailableProducts] = useState<AdminProduct[]>([]);
  const [productLoading, setProductLoading] = useState(false);
  const [productSearch, setProductSearch] = useState("");
  const [selectedProductIds, setSelectedProductIds] = useState<string[]>([]);

  const [form, setForm] = useState(defaultForm());

  useEffect(() => {
    fetchCombos();
  }, [filterCategory, filterStatus, trashMode]);

  useEffect(() => {
    fetchCategorySettings();
  }, []);

  useEffect(() => {
    if (!safeStr(form.categorySlug)) return;
    fetchAvailableProducts(form.categorySlug);
  }, [form.categorySlug]);

  useEffect(() => {
    if (!message.text) return;
    const t = setTimeout(() => setMessage({ type: "", text: "" }), 2600);
    return () => clearTimeout(t);
  }, [message]);

  async function fetchCombos() {
    try {
      setLoading(true);

      const params = new URLSearchParams();
      params.set("limit", "300");
      if (filterCategory) params.set("categorySlug", filterCategory);
      if (filterStatus) params.set("status", filterStatus);
      if (trashMode) params.set("trash", "1");

      const res = await fetch(`/api/admin/combos?${params.toString()}`, {
        credentials: "include",
        cache: "no-store",
      });

      const data: CombosResponse = await res.json().catch(() => ({}));

      if (!res.ok) {
        setCombos([]);
        setMessage({ type: "error", text: data?.error || "Failed to load combos" });
        return;
      }

      setCombos(Array.isArray(data?.combos) ? data.combos : []);
    } catch {
      setCombos([]);
      setMessage({ type: "error", text: "Network error while loading combos" });
    } finally {
      setLoading(false);
    }
  }

  async function fetchCategorySettings() {
    try {
      const res = await fetch("/api/combo-category-settings", {
        cache: "no-store",
      });

      const data: ComboCategorySettingsResponse = await res.json().catch(() => ({}));

      if (!res.ok) {
        setCategorySettingsMap({});
        return;
      }

      const rows = Array.isArray(data?.settings) ? data.settings : [];
      const next: Record<string, ComboCategorySettingRecord> = {};

      for (const row of rows) {
        const slug = safeStr(row?.categorySlug).toLowerCase();
        if (!slug) continue;
        if (!next[slug]) {
          next[slug] = row;
        }
      }

      setCategorySettingsMap(next);
    } catch {
      setCategorySettingsMap({});
    }
  }

  async function fetchAvailableProducts(categorySlug: string) {
    try {
      const productCategory = productCategoryFromCategorySlug(categorySlug);
      if (!productCategory) {
        setAvailableProducts([]);
        return;
      }

      setProductLoading(true);

      const params = new URLSearchParams();
      params.set("category", productCategory);
      params.set("limit", "500");

      const res = await fetch(`/api/admin/products?${params.toString()}`, {
        credentials: "include",
        cache: "no-store",
      });

      const data: AdminProductsResponse = await res.json().catch(() => ({}));

      if (!res.ok) {
        setAvailableProducts([]);
        return;
      }

      const nextProducts = (Array.isArray(data?.products) ? data.products : [])
        .filter((p) => !p?.deletedAt)
        .sort((a, b) => {
          const codeCmp = safeStr(a.subjectCode).localeCompare(safeStr(b.subjectCode));
          if (codeCmp !== 0) return codeCmp;
          const sessionCmp =
            sessionSortValue(safeStr(b.session6), safeStr(b.session)) -
            sessionSortValue(safeStr(a.session6), safeStr(a.session));
          if (sessionCmp !== 0) return sessionCmp;
          return safeStr(a.title).localeCompare(safeStr(b.title));
        });

      setAvailableProducts(nextProducts);
    } catch {
      setAvailableProducts([]);
    } finally {
      setProductLoading(false);
    }
  }

  async function patchComboQuick(id: string, patch: Record<string, any>, successText: string) {
    if (!id) return;

    try {
      const res = await fetch(`/api/admin/combos/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(patch),
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        setMessage({ type: "error", text: data?.error || "Failed to update combo" });
        return;
      }

      setMessage({ type: "success", text: successText });
      fetchCombos();
    } catch {
      setMessage({ type: "error", text: "Network error while updating combo" });
    }
  }

  async function handleRestoreCombo(id: string) {
    if (!id) return;

    try {
      const res = await fetch(`/api/admin/combos/${id}?action=restore`, {
        method: "POST",
        credentials: "include",
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        setMessage({ type: "error", text: data?.error || "Failed to restore combo" });
        return;
      }

      setMessage({ type: "success", text: "Combo restored ✅" });
      fetchCombos();
    } catch {
      setMessage({ type: "error", text: "Network error while restoring combo" });
    }
  }

  async function handlePurgeCombo(id: string) {
    if (!id) return;

    const ok = window.confirm("Kya aap is combo ko permanently delete karna chahte hain?");
    if (!ok) return;

    try {
      const res = await fetch(`/api/admin/combos/${id}?action=purge`, {
        method: "POST",
        credentials: "include",
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        setMessage({ type: "error", text: data?.error || "Failed to purge combo" });
        return;
      }

      setMessage({ type: "success", text: "Combo permanently deleted ✅" });
      fetchCombos();
    } catch {
      setMessage({ type: "error", text: "Network error while purging combo" });
    }
  }

  const visibleCombos = useMemo(() => {
    const q = safeStr(search).toLowerCase();
    if (!q) return combos;

    return combos.filter((c) => {
      const hay = [
        c.title,
        c.shortTitle,
        c.slug,
        c.categorySlug,
        c.categoryLabel,
        c.comboKind,
        c.subjectCode,
        c.medium,
        c.metaTitle,
        c.sourceType,
        c.generationKey,
      ]
        .map((x) => safeStr(x).toLowerCase())
        .join(" ");

      return hay.includes(q);
    });
  }, [combos, search]);

  const generatedCombos = useMemo(
    () =>
      visibleCombos.filter(
        (c) =>
          c.isAutoGenerated ||
          safeStr(c.sourceType) === "generated" ||
          safeStr(c.sourceType) === "pyq_generated"
      ),
    [visibleCombos]
  );

  const manualCombos = useMemo(
    () =>
      visibleCombos.filter(
        (c) =>
          !(
            c.isAutoGenerated ||
            safeStr(c.sourceType) === "generated" ||
            safeStr(c.sourceType) === "pyq_generated"
          )
      ),
    [visibleCombos]
  );

  const pyqGeneratedCount = useMemo(() => {
    return visibleCombos.filter(
      (c) =>
        safeStr(c.categorySlug) === "question-papers" ||
        safeStr(c.comboKind) === "pyq_3y" ||
        safeStr(c.comboKind) === "pyq_5y" ||
        safeStr(c.sourceType) === "pyq_generated"
    ).length;
  }, [visibleCombos]);

  const selectedProducts = useMemo(() => {
    const map = new Map(availableProducts.map((p) => [safeStr(p._id), p]));
    return selectedProductIds
      .map((id) => map.get(safeStr(id)))
      .filter(Boolean) as AdminProduct[];
  }, [availableProducts, selectedProductIds]);

  const filteredAvailableProducts = useMemo(() => {
    const q = safeStr(productSearch).toLowerCase();
    if (!q) return availableProducts;

    return availableProducts.filter((p) => {
      const hay = [
        p.title,
        p.subjectCode,
        p.subjectTitleEn,
        p.subjectTitleHi,
        p.language,
        p.session,
        ...(Array.isArray(p.courseCodes) ? p.courseCodes : []),
      ]
        .map((x) => safeStr(x).toLowerCase())
        .join(" ");

      return hay.includes(q);
    });
  }, [availableProducts, productSearch]);

  const selectedTotalMrp = useMemo(() => {
    return selectedProducts.reduce((acc, p) => acc + Math.max(0, Number(p.price || 0)), 0);
  }, [selectedProducts]);

  const selectedMediumLabel = useMemo(() => {
    const arr = Array.from(new Set(selectedProducts.map((p) => safeStr(p.language)).filter(Boolean)));
    return arr.length === 1 ? arr[0] : "";
  }, [selectedProducts]);

  const selectedSubjectCodeLabel = useMemo(() => {
    const arr = Array.from(
      new Set(selectedProducts.map((p) => safeStr(p.subjectCode).toUpperCase()).filter(Boolean))
    );
    return arr.length === 1 ? arr[0] : "";
  }, [selectedProducts]);

  const selectedLang3Label = useMemo(() => {
    const arr = Array.from(
      new Set(selectedProducts.map((p) => safeStr(p.lang3).toUpperCase()).filter(Boolean))
    );
    return arr.length === 1 ? arr[0] : "";
  }, [selectedProducts]);

  const selectedSessionRangeLabel = useMemo(() => {
    if (!selectedProducts.length) return "";

    const sorted = [...selectedProducts].sort(
      (a, b) =>
        sessionSortValue(safeStr(b.session6), safeStr(b.session)) -
        sessionSortValue(safeStr(a.session6), safeStr(a.session))
    );

    const first = safeStr(sorted[0]?.session);
    const last = safeStr(sorted[sorted.length - 1]?.session);

    if (first && last && first !== last) return `${first} to ${last}`;
    return first || "";
  }, [selectedProducts]);

  const currentCategorySetting = useMemo(() => {
    const slug = safeStr(form.categorySlug).toLowerCase();
    return slug ? categorySettingsMap[slug] || null : null;
  }, [categorySettingsMap, form.categorySlug]);

  const currentMasterDiscount = useMemo(() => {
    if (!isValidMasterDiscount(currentCategorySetting)) return 0;
    return Math.max(0, Math.min(100, Number(currentCategorySetting?.discountValue || 0)));
  }, [currentCategorySetting]);

  const pricingPreview = useMemo(() => {
    return calculatePricingPreview(selectedTotalMrp, currentMasterDiscount);
  }, [selectedTotalMrp, currentMasterDiscount]);

  function resetForm() {
    setEditingId("");
    setForm(defaultForm());
    setSelectedProductIds([]);
    setProductSearch("");
  }

  function toggleProductSelect(id: string) {
    const pid = safeStr(id);
    if (!pid) return;

    setSelectedProductIds((prev) => {
      if (prev.includes(pid)) {
        return prev.filter((x) => x !== pid);
      }
      return [...prev, pid];
    });
  }

  function startEdit(combo: ComboRecord) {
    const ids = Array.isArray(combo.productIds)
      ? combo.productIds.map((x) => safeStr(x)).filter(Boolean)
      : [];

    setEditingId(String(combo._id || ""));
    setForm({
      title: safeStr(combo.title),
      shortTitle: safeStr(combo.shortTitle),
      categorySlug: safeStr(combo.categorySlug) || "solved-assignments",
      comboKind: safeStr(combo.comboKind) || "admin",
      status: safeStr(combo.status) || "draft",
      subjectCode: safeStr(combo.subjectCode),
      medium: safeStr(combo.medium),
      lang3: safeStr(combo.lang3),
      sessionRangeLabel: safeStr(combo.sessionRangeLabel),
      description: safeStr(combo.description),
      shortDescription: safeStr(combo.shortDescription),
      badge: safeStr(combo.badge),
      itemsLabel: safeStr(combo.itemsLabel) || "Included Bundle Items",
      sortOrder: String(combo.sortOrder ?? 0),
      metaTitle: safeStr(combo.metaTitle),
      metaDescription: safeStr(combo.metaDescription),
      isActive: !!combo.isActive,
      isMakeOwnComboAllowed: !!combo.isMakeOwnComboAllowed,
    });
    setSelectedProductIds(ids);
    setProductSearch("");
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  async function handleCreateOrUpdateCombo() {
    if (saving) return;

    const title = safeStr(form.title);
    const categorySlug = safeStr(form.categorySlug);
    const comboKind = safeStr(form.comboKind);

    if (!title) {
      setMessage({ type: "error", text: "Title required hai." });
      return;
    }

    if (!categorySlug) {
      setMessage({ type: "error", text: "Category required hai." });
      return;
    }

    if (!comboKind) {
      setMessage({ type: "error", text: "Combo kind required hai." });
      return;
    }

    if (!currentCategorySetting?.manualCombosEnabled) {
      setMessage({
        type: "error",
        text: `${labelFromCategorySlug(categorySlug)} me manual combo abhi disabled hai.`,
      });
      return;
    }

    if (!isValidMasterDiscount(currentCategorySetting)) {
      setMessage({
        type: "error",
        text: `${labelFromCategorySlug(categorySlug)} ke liye valid master discount % set kijiye. Iske bina combo save nahi hoga.`,
      });
      return;
    }

    if (!selectedProducts.length) {
      setMessage({ type: "error", text: "Combo me kam se kam 1 real product select karna zaroori hai." });
      return;
    }

    const categoryMismatch = selectedProducts.some(
      (p) => safeStr(p.category) !== productCategoryFromCategorySlug(categorySlug)
    );

    if (categoryMismatch) {
      setMessage({ type: "error", text: "Combo me sirf selected category ke real products hi allowed hain." });
      return;
    }

    const itemsSnapshot = selectedProducts.map((p) => ({
      productId: safeStr(p._id),
      title: safeStr(p.title),
      slug: safeStr(p.slug),
      category: safeStr(p.category),
      subjectCode: safeStr(p.subjectCode).toUpperCase(),
      subjectTitleEn: safeStr(p.subjectTitleEn),
      subjectTitleHi: safeStr(p.subjectTitleHi),
      medium: safeStr(p.language),
      lang3: safeStr(p.lang3).toUpperCase(),
      session: safeStr(p.session),
      session6: safeStr(p.session6),
      courseCodes: Array.isArray(p.courseCodes)
        ? p.courseCodes.map((x) => safeStr(x).toUpperCase()).filter(Boolean)
        : [],
      courseTitles: Array.isArray(p.courseTitles)
        ? p.courseTitles.map((x) => safeStr(x)).filter(Boolean)
        : [],
      price: Math.max(0, safeNum(p.price, 0)),
      thumbUrl: buildThumbUrl(p),
    }));

    const payload = {
      title,
      shortTitle: safeStr(form.shortTitle),
      categorySlug,
      categoryLabel: labelFromCategorySlug(categorySlug),
      comboKind,
      variant: inferVariant(categorySlug, comboKind),
      status: safeStr(form.status),
      subjectCode: safeStr(form.subjectCode || selectedSubjectCodeLabel).toUpperCase(),
      medium: safeStr(form.medium || selectedMediumLabel),
      lang3: safeStr(form.lang3 || selectedLang3Label).toUpperCase(),
      sessionRangeLabel: safeStr(form.sessionRangeLabel || selectedSessionRangeLabel),
      description: safeStr(form.description),
      shortDescription: safeStr(form.shortDescription),
      badge: safeStr(form.badge),
      itemsLabel: safeStr(form.itemsLabel),
      sortOrder: safeNum(form.sortOrder, 0),
      metaTitle: safeStr(form.metaTitle),
      metaDescription: safeStr(form.metaDescription),
      isActive: !!form.isActive,
      isAutoGenerated: false,
      isMakeOwnComboAllowed: !!form.isMakeOwnComboAllowed,
      isLockedByAdmin: false,
      allowAutoRefresh: false,
      productIds: selectedProducts.map((p) => safeStr(p._id)).filter(Boolean),
      itemsSnapshot,
      rules: {
        minProductsRequired: comboKind === "custom" ? 1 : 0,
        sameSubjectOnly: comboKind === "pyq_3y" || comboKind === "pyq_5y",
        sameMediumOnly: comboKind === "pyq_3y" || comboKind === "pyq_5y",
        sameCategoryOnly: true,
        useLatestSessionsOnly: comboKind === "pyq_3y" || comboKind === "pyq_5y",
        latestProductCount: comboKind === "pyq_3y" ? 6 : comboKind === "pyq_5y" ? 10 : 0,
      },
    };

    try {
      setSaving(true);

      const isEdit = !!editingId;
      const url = isEdit ? `/api/admin/combos/${editingId}` : "/api/admin/combos";
      const method = isEdit ? "PATCH" : "POST";

      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(payload),
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        setMessage({
          type: "error",
          text: data?.error || `Failed to ${isEdit ? "update" : "create"} combo`,
        });
        return;
      }

      setMessage({ type: "success", text: isEdit ? "Combo updated ✅" : "Combo created ✅" });
      resetForm();
      fetchCombos();
    } catch {
      setMessage({
        type: "error",
        text: `Network error while ${editingId ? "updating" : "creating"} combo`,
      });
    } finally {
      setSaving(false);
    }
  }

  async function handleTrashCombo(id: string) {
    if (!id || deletingId) return;

    const ok = window.confirm("Kya aap is combo ko trash me bhejna chahte hain?");
    if (!ok) return;

    try {
      setDeletingId(id);

      const res = await fetch(`/api/admin/combos/${id}`, {
        method: "DELETE",
        credentials: "include",
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        setMessage({ type: "error", text: data?.error || "Failed to move combo to trash" });
        return;
      }

      if (editingId === id) {
        resetForm();
      }

      setMessage({ type: "success", text: "Combo moved to trash ✅" });
      fetchCombos();
    } catch {
      setMessage({ type: "error", text: "Network error while deleting combo" });
    } finally {
      setDeletingId("");
    }
  }

  return (
    <main className="min-h-screen bg-gray-100 text-slate-900">
      <div className="max-w-7xl mx-auto px-4 py-10">
        <div className="rounded-3xl bg-white border border-gray-200 p-6 shadow-sm">
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <div className="text-2xl font-extrabold flex items-center gap-2">
                <Boxes className="text-violet-700" />
                Combos Admin
              </div>
              <div className="text-sm text-slate-600 mt-1">
                Manual combo creation, auto PYQ combo monitoring aur combo inventory yahin se manage kijiye.
              </div>
            </div>

            <div className="flex items-center gap-2 flex-wrap">
              <button
                type="button"
                onClick={() => {
                  fetchCombos();
                  fetchCategorySettings();
                }}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white hover:bg-gray-50 border border-gray-200 transition font-semibold shadow-sm"
              >
                <RefreshCcw size={16} />
                Refresh
              </button>

              <button
                type="button"
                onClick={() => setTrashMode((p) => !p)}
                className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl transition font-semibold shadow-sm ${
                  trashMode
                    ? "bg-red-600 hover:bg-red-700 text-white"
                    : "bg-white hover:bg-gray-50 border border-gray-200"
                }`}
              >
                <Archive size={16} />
                {trashMode ? "Exit Trash View" : "Open Trash"}
              </button>

              <Link
                href="/admin/combo-category-settings"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-blue-700 hover:bg-blue-800 text-white transition font-semibold shadow-sm"
              >
                <SlidersHorizontal size={16} />
                Category Settings
              </Link>

              <Link
                href="/admin"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white hover:bg-gray-50 border border-gray-200 transition font-semibold shadow-sm"
              >
                <ArrowRight size={18} />
                Back to Admin
              </Link>
            </div>
          </div>

          {message.text ? (
            <div
              className={`mt-6 rounded-2xl border p-4 flex items-start gap-3 ${
                message.type === "success"
                  ? "border-emerald-200 bg-emerald-50"
                  : "border-red-200 bg-red-50"
              }`}
            >
              {message.type === "success" ? (
                <CheckCircle2 className="text-emerald-700 mt-0.5" size={18} />
              ) : (
                <AlertCircle className="text-red-700 mt-0.5" size={18} />
              )}
              <div className="text-sm font-extrabold text-slate-900">{message.text}</div>
            </div>
          ) : null}

          <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 shadow-sm">
              <div className="flex items-center gap-3">
                <PackageCheck className="text-blue-700" />
                <div>
                  <div className="font-extrabold text-blue-900">Manual Combos</div>
                  <div className="text-xs text-slate-600 mt-1">
                    Admin khud combo create aur edit kar sakta hai
                  </div>
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 shadow-sm">
              <div className="flex items-center gap-3">
                <ShieldCheck className="text-emerald-700" />
                <div>
                  <div className="font-extrabold text-emerald-900">PYQ Auto Mode</div>
                  <div className="text-xs text-slate-600 mt-1">
                    3Y / 5Y PYQ combos automatically sync honge
                  </div>
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-violet-200 bg-violet-50 p-5 shadow-sm">
              <div className="flex items-center gap-3">
                <SlidersHorizontal className="text-violet-700" />
                <div>
                  <div className="font-extrabold text-violet-900">Category Controls</div>
                  <div className="text-xs text-slate-600 mt-1">
                    Discount aur make your own combo rules category setting se ayenge
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-6 grid grid-cols-1 xl:grid-cols-[480px_1fr] gap-6">
            {!trashMode ? (
              <div className="rounded-3xl border border-gray-200 bg-gray-50 p-5">
                <div className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-2">
                    {editingId ? <Pencil className="text-slate-700" size={18} /> : <Plus className="text-slate-700" size={18} />}
                    <div className="text-lg font-extrabold text-slate-900">
                      {editingId ? "Edit Manual Combo" : "Create Manual Combo"}
                    </div>
                  </div>

                  {editingId ? (
                    <button
                      type="button"
                      onClick={resetForm}
                      className="inline-flex items-center gap-2 px-3 py-2 rounded-xl bg-white hover:bg-gray-50 border border-gray-200 font-bold text-sm"
                    >
                      Cancel
                    </button>
                  ) : null}
                </div>

                <div className="mt-5 space-y-4">
                  <div>
                    <label className="text-xs font-extrabold text-slate-600 uppercase">Title</label>
                    <input
                      value={form.title}
                      onChange={(e) => setForm((p) => ({ ...p, title: e.target.value }))}
                      className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                      placeholder="Combo title"
                    />
                  </div>

                  <div>
                    <label className="text-xs font-extrabold text-slate-600 uppercase">Short Title</label>
                    <input
                      value={form.shortTitle}
                      onChange={(e) => setForm((p) => ({ ...p, shortTitle: e.target.value }))}
                      className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                      placeholder="Short title"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Category</label>
                      <select
                        value={form.categorySlug}
                        onChange={(e) => {
                          setForm((p) => ({ ...p, categorySlug: e.target.value }));
                          setSelectedProductIds([]);
                          setProductSearch("");
                        }}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                      >
                        {CATEGORY_OPTIONS.map((x) => (
                          <option key={x.value} value={x.value}>
                            {x.label}
                          </option>
                        ))}
                      </select>
                    </div>

                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Combo Kind</label>
                      <select
                        value={form.comboKind}
                        onChange={(e) => setForm((p) => ({ ...p, comboKind: e.target.value }))}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                      >
                        {COMBO_KIND_OPTIONS.map((x) => (
                          <option key={x.value} value={x.value}>
                            {x.label}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Status</label>
                      <select
                        value={form.status}
                        onChange={(e) => setForm((p) => ({ ...p, status: e.target.value }))}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                      >
                        {STATUS_OPTIONS.map((x) => (
                          <option key={x.value} value={x.value}>
                            {x.label}
                          </option>
                        ))}
                      </select>
                    </div>

                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Sort Order</label>
                      <input
                        value={form.sortOrder}
                        onChange={(e) => setForm((p) => ({ ...p, sortOrder: e.target.value }))}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                        placeholder="0"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-3">
                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Subject Code</label>
                      <input
                        value={form.subjectCode}
                        onChange={(e) => setForm((p) => ({ ...p, subjectCode: e.target.value }))}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                        placeholder="Auto from selected"
                      />
                    </div>

                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Medium</label>
                      <input
                        value={form.medium}
                        onChange={(e) => setForm((p) => ({ ...p, medium: e.target.value }))}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                        placeholder="Auto from selected"
                      />
                    </div>

                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Lang3</label>
                      <input
                        value={form.lang3}
                        onChange={(e) => setForm((p) => ({ ...p, lang3: e.target.value }))}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                        placeholder="Auto from selected"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="text-xs font-extrabold text-slate-600 uppercase">Session Range Label</label>
                    <input
                      value={form.sessionRangeLabel}
                      onChange={(e) => setForm((p) => ({ ...p, sessionRangeLabel: e.target.value }))}
                      className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                      placeholder="Auto from selected sessions"
                    />
                  </div>

                  <div>
                    <label className="text-xs font-extrabold text-slate-600 uppercase">Description</label>
                    <textarea
                      value={form.description}
                      onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))}
                      className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none min-h-[100px]"
                      placeholder="Combo description"
                    />
                  </div>

                  <div>
                    <label className="text-xs font-extrabold text-slate-600 uppercase">Short Description</label>
                    <textarea
                      value={form.shortDescription}
                      onChange={(e) => setForm((p) => ({ ...p, shortDescription: e.target.value }))}
                      className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none min-h-[80px]"
                      placeholder="Short description"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Badge</label>
                      <input
                        value={form.badge}
                        onChange={(e) => setForm((p) => ({ ...p, badge: e.target.value }))}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                        placeholder="Latest 6 Products"
                      />
                    </div>

                    <div>
                      <label className="text-xs font-extrabold text-slate-600 uppercase">Items Label</label>
                      <input
                        value={form.itemsLabel}
                        onChange={(e) => setForm((p) => ({ ...p, itemsLabel: e.target.value }))}
                        className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                        placeholder="Included Bundle Items"
                      />
                    </div>
                  </div>

                  <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4">
                    <div className="flex items-center justify-between gap-3 flex-wrap">
                      <div>
                        <div className="text-sm font-extrabold text-emerald-900">
                          Category Master Discount Pricing
                        </div>
                        <div className="text-xs font-semibold text-emerald-800 mt-1">
                          Pricing sirf category setting ke master discount % se auto-calculate hogi.
                        </div>
                      </div>
                      <div className="text-sm font-extrabold text-emerald-900">
                        Discount: {currentMasterDiscount > 0 ? `${currentMasterDiscount}%` : "Not Set"}
                      </div>
                    </div>

                    {!isValidMasterDiscount(currentCategorySetting) ? (
                      <div className="mt-3 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-extrabold text-red-700">
                        Is category ke liye valid master discount % set nahi hai. Pehle Category Settings me jaakar discount save kijiye.
                      </div>
                    ) : null}

                    <div className="mt-4 grid grid-cols-3 gap-3">
                      <div>
                        <label className="text-xs font-extrabold text-slate-600 uppercase">Total MRP</label>
                        <input
                          value={selectedProducts.length ? String(pricingPreview.totalMrp) : ""}
                          readOnly
                          className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-100 px-4 py-3 outline-none cursor-not-allowed"
                          placeholder="Auto from selected products"
                        />
                      </div>

                      <div>
                        <label className="text-xs font-extrabold text-slate-600 uppercase">Offer Price</label>
                        <input
                          value={selectedProducts.length && currentMasterDiscount > 0 ? String(pricingPreview.offerPrice) : ""}
                          readOnly
                          className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-100 px-4 py-3 outline-none cursor-not-allowed"
                          placeholder="Auto from master discount"
                        />
                      </div>

                      <div>
                        <label className="text-xs font-extrabold text-slate-600 uppercase">Save %</label>
                        <input
                          value={selectedProducts.length && currentMasterDiscount > 0 ? String(pricingPreview.savePercent) : ""}
                          readOnly
                          className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-100 px-4 py-3 outline-none cursor-not-allowed"
                          placeholder="Auto from master discount"
                        />
                      </div>
                    </div>

                    <div className="mt-3 text-xs font-bold text-slate-600">
                      Save Amount: ₹{money(pricingPreview.saveAmount)}
                    </div>
                  </div>

                  <div>
                    <label className="text-xs font-extrabold text-slate-600 uppercase">Meta Title</label>
                    <input
                      value={form.metaTitle}
                      onChange={(e) => setForm((p) => ({ ...p, metaTitle: e.target.value }))}
                      className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                      placeholder="Meta title"
                    />
                  </div>

                  <div>
                    <label className="text-xs font-extrabold text-slate-600 uppercase">Meta Description</label>
                    <textarea
                      value={form.metaDescription}
                      onChange={(e) => setForm((p) => ({ ...p, metaDescription: e.target.value }))}
                      className="mt-2 w-full rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none min-h-[90px]"
                      placeholder="Meta description"
                    />
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <label className="flex items-center gap-2 rounded-2xl border border-gray-200 bg-white px-4 py-3 font-semibold">
                      <input
                        type="checkbox"
                        checked={form.isActive}
                        onChange={(e) => setForm((p) => ({ ...p, isActive: e.target.checked }))}
                      />
                      Active
                    </label>

                    <label className="flex items-center gap-2 rounded-2xl border border-gray-200 bg-white px-4 py-3 font-semibold">
                      <input
                        type="checkbox"
                        checked={form.isMakeOwnComboAllowed}
                        onChange={(e) =>
                          setForm((p) => ({ ...p, isMakeOwnComboAllowed: e.target.checked }))
                        }
                      />
                      Make Own Combo
                    </label>
                  </div>

                  <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4">
                    <div className="flex items-center gap-2 text-sm font-extrabold text-blue-900">
                      <PackageCheck size={16} />
                      Real Products Selector
                    </div>
                    <div className="mt-1 text-xs font-semibold text-blue-800">
                      Yahan sirf same category ke real products aa rahe hain. Combo me fake ya external item add nahi ho sakta.
                    </div>

                    <div className="mt-3 flex items-center gap-2 rounded-2xl border border-blue-200 bg-white px-4 py-3">
                      <Search size={15} className="text-slate-400" />
                      <input
                        value={productSearch}
                        onChange={(e) => setProductSearch(e.target.value)}
                        className="w-full outline-none text-sm"
                        placeholder="Search real products by title, subject code, medium, course code..."
                      />
                    </div>

                    <div className="mt-3 rounded-2xl border border-blue-200 bg-white p-3 max-h-[360px] overflow-auto">
                      {productLoading ? (
                        <div className="py-8 text-center text-sm font-extrabold text-slate-600">
                          Loading products...
                        </div>
                      ) : filteredAvailableProducts.length === 0 ? (
                        <div className="py-8 text-center text-sm font-extrabold text-slate-600">
                          No real products found
                        </div>
                      ) : (
                        <div className="space-y-2">
                          {filteredAvailableProducts.map((product) => {
                            const id = safeStr(product._id);
                            const checked = selectedProductIds.includes(id);
                            const thumb = buildThumbUrl(product);

                            return (
                              <label
                                key={id}
                                className={`flex items-start gap-3 rounded-2xl border p-3 cursor-pointer transition ${
                                  checked
                                    ? "border-blue-400 bg-blue-50"
                                    : "border-gray-200 bg-white hover:bg-gray-50"
                                }`}
                              >
                                <input
                                  type="checkbox"
                                  checked={checked}
                                  onChange={() => toggleProductSelect(id)}
                                  className="mt-1"
                                />

                                <div className="relative h-16 w-14 shrink-0 overflow-hidden rounded-xl border border-gray-200 bg-slate-100">
                                  {thumb ? (
                                    <Image
                                      src={thumb}
                                      alt={safeStr(product.title) || "Product"}
                                      fill
                                      sizes="56px"
                                      className="object-cover"
                                    />
                                  ) : null}
                                </div>

                                <div className="min-w-0 flex-1">
                                  <div className="text-sm font-extrabold text-slate-900 line-clamp-2">
                                    {safeStr(product.title) || "Untitled Product"}
                                  </div>
                                  <div className="mt-1 text-xs font-semibold text-slate-600">
                                    {[
                                      safeStr(product.subjectCode).toUpperCase(),
                                      safeStr(product.language),
                                      safeStr(product.session),
                                    ]
                                      .filter(Boolean)
                                      .join(" • ") || "-"}
                                  </div>
                                  <div className="mt-1 text-xs font-bold text-blue-700">
                                    ₹{money(Number(product.price || 0))}
                                  </div>
                                </div>
                              </label>
                            );
                          })}
                        </div>
                      )}
                    </div>

                    <div className="mt-3 rounded-2xl border border-blue-200 bg-white p-3">
                      <div className="text-xs uppercase font-extrabold text-slate-500">
                        Selected real products
                      </div>
                      <div className="mt-2 text-sm font-extrabold text-slate-900">
                        {selectedProducts.length} items selected
                      </div>
                      {selectedProducts.length ? (
                        <div className="mt-3 grid grid-cols-1 gap-2">
                          {selectedProducts.map((p) => (
                            <div
                              key={safeStr(p._id)}
                              className="rounded-xl border border-gray-200 bg-gray-50 px-3 py-2"
                            >
                              <div className="text-sm font-extrabold text-slate-900">
                                {safeStr(p.title)}
                              </div>
                              <div className="text-xs font-semibold text-slate-600 mt-0.5">
                                {[safeStr(p.subjectCode), safeStr(p.language), safeStr(p.session)]
                                  .filter(Boolean)
                                  .join(" • ") || "-"}
                              </div>
                            </div>
                          ))}
                        </div>
                      ) : null}
                    </div>
                  </div>

                  <div className="flex items-center gap-3 flex-wrap">
                    <button
                      type="button"
                      onClick={handleCreateOrUpdateCombo}
                      disabled={saving || !isValidMasterDiscount(currentCategorySetting)}
                      className="inline-flex items-center gap-2 px-5 py-3 rounded-2xl bg-violet-700 hover:bg-violet-800 text-white font-extrabold transition shadow-sm disabled:opacity-60"
                    >
                      {editingId ? <Pencil size={16} /> : <Plus size={16} />}
                      {saving ? (editingId ? "Updating..." : "Creating...") : editingId ? "Update Combo" : "Create Combo"}
                    </button>

                    <button
                      type="button"
                      onClick={resetForm}
                      className="inline-flex items-center gap-2 px-5 py-3 rounded-2xl bg-white hover:bg-gray-50 border border-gray-200 font-extrabold transition shadow-sm"
                    >
                      <X size={16} />
                      Reset
                    </button>
                  </div>
                </div>
              </div>
            ) : null}

            <div className="space-y-6">
              <SectionCard
                title={trashMode ? "Combo Trash Filters" : "Combo Inventory Filters"}
                subtitle={
                  trashMode
                    ? "Trash me gaye combos ko restore ya permanently delete kijiye."
                    : "Manual aur generated dono combos ko yahin se filter kijiye."
                }
                icon={<Archive className="text-slate-700" size={20} />}
              >
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  <div className="md:col-span-2">
                    <div className="flex items-center gap-2 rounded-2xl border border-gray-200 bg-white px-4 py-3">
                      <Search size={16} className="text-gray-400" />
                      <input
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="w-full outline-none"
                        placeholder="Search combo title, slug, type, subject..."
                      />
                    </div>
                  </div>

                  <select
                    value={filterCategory}
                    onChange={(e) => setFilterCategory(e.target.value)}
                    className="rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                  >
                    <option value="">All Categories</option>
                    {CATEGORY_OPTIONS.map((x) => (
                      <option key={x.value} value={x.value}>
                        {x.label}
                      </option>
                    ))}
                  </select>

                  <select
                    value={filterStatus}
                    onChange={(e) => setFilterStatus(e.target.value)}
                    className="rounded-2xl border border-gray-200 bg-white px-4 py-3 outline-none"
                  >
                    <option value="">All Status</option>
                    {STATUS_OPTIONS.map((x) => (
                      <option key={x.value} value={x.value}>
                        {x.label}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="mt-4 grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div className="rounded-2xl border border-gray-200 bg-gray-50 p-4">
                    <div className="text-[11px] uppercase font-extrabold text-slate-500">
                      {trashMode ? "Trash Visible" : "All Visible"}
                    </div>
                    <div className="mt-1 text-lg font-extrabold text-slate-900">{visibleCombos.length}</div>
                  </div>
                  <div className="rounded-2xl border border-gray-200 bg-gray-50 p-4">
                    <div className="text-[11px] uppercase font-extrabold text-slate-500">Generated</div>
                    <div className="mt-1 text-lg font-extrabold text-slate-900">{generatedCombos.length}</div>
                  </div>
                  <div className="rounded-2xl border border-gray-200 bg-gray-50 p-4">
                    <div className="text-[11px] uppercase font-extrabold text-slate-500">Manual</div>
                    <div className="mt-1 text-lg font-extrabold text-slate-900">{manualCombos.length}</div>
                  </div>
                </div>
              </SectionCard>

              {!trashMode ? (
                <SectionCard
                  title="PYQ Auto Status"
                  subtitle="Question Papers category me same subject code + same medium ke latest PYQ products milte hi combos auto sync honge."
                  icon={<ShieldCheck className="text-emerald-700" size={20} />}
                >
                  <div className="grid sm:grid-cols-3 gap-3">
                    <div className="rounded-2xl border border-gray-200 bg-gray-50 p-4">
                      <div className="text-[11px] uppercase font-extrabold text-slate-500">Detected PYQ Combos</div>
                      <div className="mt-1 text-lg font-extrabold text-slate-900">{pyqGeneratedCount}</div>
                    </div>
                    <div className="rounded-2xl border border-gray-200 bg-gray-50 p-4">
                      <div className="text-[11px] uppercase font-extrabold text-slate-500">Rule Type</div>
                      <div className="mt-1 text-sm font-extrabold text-slate-900">Latest 6 / Latest 10</div>
                    </div>
                    <div className="rounded-2xl border border-gray-200 bg-gray-50 p-4">
                      <div className="text-[11px] uppercase font-extrabold text-slate-500">Manual Action</div>
                      <div className="mt-1 text-sm font-extrabold text-emerald-700">Not Required</div>
                    </div>
                  </div>
                </SectionCard>
              ) : null}

              {trashMode ? (
                <SectionCard
                  title="Trashed Combos"
                  subtitle="Yahan se restore aur purge dono control kar sakte ho."
                  icon={<Archive className="text-red-700" size={20} />}
                >
                  <div className="space-y-4">
                    {loading ? (
                      <div className="rounded-2xl border border-gray-200 bg-white p-8 text-center font-extrabold text-slate-600">
                        Loading trashed combos...
                      </div>
                    ) : visibleCombos.length === 0 ? (
                      <div className="rounded-2xl border border-gray-200 bg-white p-8 text-center">
                        <div className="font-extrabold text-slate-900">Trash is empty</div>
                        <div className="text-sm text-slate-600 mt-1">Deleted combos yahan dikhengi.</div>
                      </div>
                    ) : (
                      visibleCombos.map((combo, index) => (
                        <div
                          key={combo._id || `${combo.slug}-${index}`}
                          className="rounded-2xl border border-red-200 bg-white p-5 shadow-sm"
                        >
                          <div className="flex items-start justify-between gap-4 flex-wrap">
                            <div className="min-w-0">
                              <div className="flex items-center gap-2 flex-wrap">
                                <span className="inline-flex items-center rounded-full bg-red-600 text-white px-3 py-1 text-[11px] font-extrabold">
                                  trashed
                                </span>
                                <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                  {safeStr(combo.comboKind) || "combo"}
                                </span>
                              </div>

                              <div className="mt-3 text-lg font-extrabold text-slate-900">
                                {combo.title || "Untitled Combo"}
                              </div>

                              <div className="mt-1 text-xs font-bold text-slate-500 break-all">
                                {combo.slug || "-"}
                              </div>
                            </div>

                            <div className="flex items-center gap-2 flex-wrap">
                              <button
                                type="button"
                                onClick={() => handleRestoreCombo(String(combo._id || ""))}
                                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold transition shadow-sm"
                              >
                                <RotateCcw size={15} />
                                Restore
                              </button>

                              <button
                                type="button"
                                onClick={() => handlePurgeCombo(String(combo._id || ""))}
                                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-red-600 hover:bg-red-700 text-white font-extrabold transition shadow-sm"
                              >
                                <Trash2 size={15} />
                                Purge
                              </button>
                            </div>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </SectionCard>
              ) : (
                <>
                  <SectionCard
                    title="Generated Combos"
                    subtitle="Yahan PYQ auto combos aur future generated combos dikhte rahenge."
                    icon={<ShieldCheck className="text-orange-700" size={20} />}
                  >
                    <div className="space-y-4">
                      {loading ? (
                        <div className="rounded-2xl border border-gray-200 bg-white p-8 text-center font-extrabold text-slate-600">
                          Loading generated combos...
                        </div>
                      ) : generatedCombos.length === 0 ? (
                        <div className="rounded-2xl border border-gray-200 bg-white p-8 text-center">
                          <div className="font-extrabold text-slate-900">No generated combos found</div>
                          <div className="text-sm text-slate-600 mt-1">
                            Auto combos yahan visible honge.
                          </div>
                        </div>
                      ) : (
                        generatedCombos.map((combo, index) => (
                          <div
                            key={combo._id || `${combo.slug}-${index}`}
                            className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"
                          >
                            <div className="flex items-start justify-between gap-4 flex-wrap">
                              <div className="min-w-0">
                                <div className="flex items-center gap-2 flex-wrap">
                                  <span className="inline-flex items-center rounded-full bg-orange-600 text-white px-3 py-1 text-[11px] font-extrabold">
                                    generated
                                  </span>

                                  <span
                                    className={`inline-flex items-center rounded-full px-3 py-1 text-[11px] font-extrabold ${
                                      combo.status === "active"
                                        ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                                        : combo.status === "inactive"
                                        ? "bg-amber-50 text-amber-700 border border-amber-200"
                                        : "bg-slate-100 text-slate-600 border border-slate-200"
                                    }`}
                                  >
                                    {combo.status || "draft"}
                                  </span>

                                  {combo.isLockedByAdmin ? (
                                    <span className="inline-flex items-center gap-1 rounded-full bg-amber-50 text-amber-700 border border-amber-200 px-3 py-1 text-[11px] font-extrabold">
                                      <Lock size={12} />
                                      locked
                                    </span>
                                  ) : null}
                                </div>

                                <div className="mt-3 text-lg font-extrabold text-slate-900">
                                  {combo.title || "Untitled Combo"}
                                </div>

                                <div className="mt-1 text-xs font-bold text-slate-500 break-all">
                                  slug: {combo.slug || "-"}
                                </div>

                                {safeStr(combo.generationKey) ? (
                                  <div className="mt-1 text-xs font-bold text-orange-700 break-all">
                                    generationKey: {safeStr(combo.generationKey)}
                                  </div>
                                ) : null}

                                <div className="mt-3 flex flex-wrap gap-2">
                                  <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                    {labelFromCategorySlug(safeStr(combo.categorySlug))}
                                  </span>

                                  {combo.subjectCode ? (
                                    <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                      {combo.subjectCode}
                                    </span>
                                  ) : null}

                                  {combo.medium ? (
                                    <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                      {combo.medium}
                                    </span>
                                  ) : null}

                                  {combo.sessionRangeLabel ? (
                                    <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                      {combo.sessionRangeLabel}
                                    </span>
                                  ) : null}
                                </div>
                              </div>

                              <div className="rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 min-w-[200px]">
                                <div className="text-[11px] uppercase font-extrabold text-slate-500">Pricing</div>
                                <div className="mt-1 text-sm font-extrabold text-slate-900">
                                  Offer: ₹{money(Number(combo.offerPrice || 0))}
                                </div>
                                <div className="text-xs font-semibold text-slate-600 mt-1">
                                  MRP: ₹{money(Number(combo.totalMrp || 0))} • Save {Number(combo.savePercent || 0)}%
                                </div>
                              </div>
                            </div>

                            {combo.description ? (
                              <div className="mt-4 text-sm text-slate-600 leading-relaxed">{combo.description}</div>
                            ) : null}

                            {Array.isArray(combo.itemsSnapshot) && combo.itemsSnapshot.length > 0 ? (
                              <div className="mt-4">
                                <div className="text-[11px] uppercase font-extrabold text-slate-500">
                                  Included items preview
                                </div>
                                <div className="mt-2 grid md:grid-cols-2 gap-2">
                                  {combo.itemsSnapshot.slice(0, 6).map((item, idx) => (
                                    <div
                                      key={`${item.title}-${idx}`}
                                      className="rounded-xl border border-gray-200 bg-gray-50 px-3 py-2"
                                    >
                                      <div className="text-sm font-extrabold text-slate-900">
                                        {safeStr(item.title) || "Untitled Item"}
                                      </div>
                                      <div className="text-xs font-semibold text-slate-600 mt-0.5">
                                        {[safeStr(item.medium), safeStr(item.session), safeStr(item.subjectCode)]
                                          .filter(Boolean)
                                          .join(" • ") || "-"}
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            ) : null}

                            <div className="mt-4 flex items-center gap-3 flex-wrap">
                              <button
                                type="button"
                                onClick={() =>
                                  patchComboQuick(
                                    String(combo._id || ""),
                                    { isLockedByAdmin: !combo.isLockedByAdmin },
                                    !combo.isLockedByAdmin
                                      ? "Combo locked by admin ✅"
                                      : "Combo unlocked ✅"
                                  )
                                }
                                className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl font-extrabold transition shadow-sm ${
                                  combo.isLockedByAdmin
                                    ? "bg-amber-600 hover:bg-amber-700 text-white"
                                    : "bg-white hover:bg-gray-50 border border-gray-200 text-slate-800"
                                }`}
                              >
                                {combo.isLockedByAdmin ? <Unlock size={15} /> : <Lock size={15} />}
                                {combo.isLockedByAdmin ? "Unlock Admin Lock" : "Lock by Admin"}
                              </button>

                              <button
                                type="button"
                                onClick={() =>
                                  patchComboQuick(
                                    String(combo._id || ""),
                                    { allowAutoRefresh: !combo.allowAutoRefresh },
                                    !combo.allowAutoRefresh
                                      ? "Auto refresh enabled ✅"
                                      : "Auto refresh disabled ✅"
                                  )
                                }
                                className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl font-extrabold transition shadow-sm ${
                                  combo.allowAutoRefresh
                                    ? "bg-emerald-600 hover:bg-emerald-700 text-white"
                                    : "bg-white hover:bg-gray-50 border border-gray-200 text-slate-800"
                                }`}
                              >
                                <RefreshCcw size={15} />
                                {combo.allowAutoRefresh ? "Disable Auto Refresh" : "Enable Auto Refresh"}
                              </button>

                              <button
                                type="button"
                                onClick={() => startEdit(combo)}
                                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-violet-700 hover:bg-violet-800 text-white font-extrabold transition shadow-sm"
                              >
                                <Pencil size={15} />
                                Edit
                              </button>

                              <button
                                type="button"
                                onClick={() => handleTrashCombo(String(combo._id || ""))}
                                disabled={deletingId === String(combo._id || "")}
                                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-red-600 hover:bg-red-700 text-white font-extrabold transition shadow-sm disabled:opacity-60"
                              >
                                <Trash2 size={15} />
                                {deletingId === String(combo._id || "") ? "Trashing..." : "Trash"}
                              </button>
                            </div>
                          </div>
                        ))
                      )}
                    </div>
                  </SectionCard>

                  <SectionCard
                    title="Manual / Admin Combos"
                    subtitle="Hand-created combos aur manually controlled entries."
                    icon={<Boxes className="text-violet-700" size={20} />}
                  >
                    <div className="space-y-4">
                      {loading ? (
                        <div className="rounded-2xl border border-gray-200 bg-white p-8 text-center font-extrabold text-slate-600">
                          Loading manual combos...
                        </div>
                      ) : manualCombos.length === 0 ? (
                        <div className="rounded-2xl border border-gray-200 bg-white p-8 text-center">
                          <div className="font-extrabold text-slate-900">No manual combos found</div>
                          <div className="text-sm text-slate-600 mt-1">Manual/admin combo entries yahan dikhengi.</div>
                        </div>
                      ) : (
                        manualCombos.map((combo, index) => (
                          <div
                            key={combo._id || `${combo.slug}-${index}`}
                            className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"
                          >
                            <div className="flex items-start justify-between gap-4 flex-wrap">
                              <div className="min-w-0">
                                <div className="flex items-center gap-2 flex-wrap">
                                  <span className="inline-flex items-center rounded-full bg-slate-900 text-white px-3 py-1 text-[11px] font-extrabold">
                                    {combo.comboKind || "combo"}
                                  </span>

                                  <span
                                    className={`inline-flex items-center rounded-full px-3 py-1 text-[11px] font-extrabold ${
                                      combo.status === "active"
                                        ? "bg-emerald-50 text-emerald-700 border border-emerald-200"
                                        : combo.status === "inactive"
                                        ? "bg-amber-50 text-amber-700 border border-amber-200"
                                        : "bg-slate-100 text-slate-600 border border-slate-200"
                                    }`}
                                  >
                                    {combo.status || "draft"}
                                  </span>
                                </div>

                                <div className="mt-3 text-lg font-extrabold text-slate-900">
                                  {combo.title || "Untitled Combo"}
                                </div>

                                <div className="mt-1 text-xs font-bold text-slate-500 break-all">
                                  {combo.slug || "-"}
                                </div>

                                <div className="mt-3 flex flex-wrap gap-2">
                                  <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                    {labelFromCategorySlug(safeStr(combo.categorySlug))}
                                  </span>

                                  {combo.subjectCode ? (
                                    <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                      {combo.subjectCode}
                                    </span>
                                  ) : null}

                                  {combo.medium ? (
                                    <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                      {combo.medium}
                                    </span>
                                  ) : null}

                                  {combo.sessionRangeLabel ? (
                                    <span className="inline-flex items-center rounded-full bg-gray-50 border border-gray-200 px-3 py-1 text-[11px] font-extrabold text-slate-700">
                                      {combo.sessionRangeLabel}
                                    </span>
                                  ) : null}
                                </div>
                              </div>

                              <div className="rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 min-w-[180px]">
                                <div className="text-[11px] uppercase font-extrabold text-slate-500">Pricing</div>
                                <div className="mt-1 text-sm font-extrabold text-slate-900">
                                  Offer: ₹{money(Number(combo.offerPrice || 0))}
                                </div>
                                <div className="text-xs font-semibold text-slate-600 mt-1">
                                  MRP: ₹{money(Number(combo.totalMrp || 0))} • Save {Number(combo.savePercent || 0)}%
                                </div>
                              </div>
                            </div>

                            {combo.description ? (
                              <div className="mt-4 text-sm text-slate-600 leading-relaxed">{combo.description}</div>
                            ) : null}

                            {Array.isArray(combo.itemsSnapshot) && combo.itemsSnapshot.length > 0 ? (
                              <div className="mt-4">
                                <div className="text-[11px] uppercase font-extrabold text-slate-500">
                                  Included real products preview
                                </div>
                                <div className="mt-2 grid md:grid-cols-2 gap-2">
                                  {combo.itemsSnapshot.slice(0, 6).map((item, idx) => (
                                    <div
                                      key={`${item.title}-${idx}`}
                                      className="rounded-xl border border-gray-200 bg-gray-50 px-3 py-2"
                                    >
                                      <div className="text-sm font-extrabold text-slate-900">
                                        {safeStr(item.title) || "Untitled Item"}
                                      </div>
                                      <div className="text-xs font-semibold text-slate-600 mt-0.5">
                                        {[safeStr(item.medium), safeStr(item.session), safeStr(item.subjectCode)]
                                          .filter(Boolean)
                                          .join(" • ") || "-"}
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            ) : null}

                            <div className="mt-4 flex items-center gap-3 flex-wrap">
                              <button
                                type="button"
                                onClick={() => startEdit(combo)}
                                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-violet-700 hover:bg-violet-800 text-white font-extrabold transition shadow-sm"
                              >
                                <Pencil size={15} />
                                Edit
                              </button>

                              <button
                                type="button"
                                onClick={() => handleTrashCombo(String(combo._id || ""))}
                                disabled={deletingId === String(combo._id || "")}
                                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-red-600 hover:bg-red-700 text-white font-extrabold transition shadow-sm disabled:opacity-60"
                              >
                                <Trash2 size={15} />
                                {deletingId === String(combo._id || "") ? "Trashing..." : "Trash"}
                              </button>
                            </div>
                          </div>
                        ))
                      )}
                    </div>
                  </SectionCard>
                </>
              )}
            </div>
          </div>

          <div className="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-5">
            <div className="flex items-start gap-3">
              <ShieldCheck className="text-blue-700 mt-0.5" size={18} />
              <div>
                <div className="font-extrabold text-blue-900">Current concept</div>
                <div className="text-sm text-slate-700 mt-1 leading-relaxed">
                  PYQ combos auto mode me chalenge. Non-PYQ combos admin manually create karega. Make Your Own Combo section category settings ke minimum rules ke hisaab se chalega.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}